#soap:
#  encrypt: true
#  sign: true
#  address: http://localhost:8881
#
rest:
  na:
    address: http://localhost:8888
  rekvirent:
    address: http://localhost:8889
  utleverer:
    address: http://localhost:8890

use:
  jwk: true

server:
  port: 8081