rekvirent:
  encrypt: true
  sign: true
  address: http://localhost:8881

utleverer:
  encrypt: true
  sign: true
  address: http://localhost:8882

na:
  encrypt: true
  sign: true
  address: http://localhost:8883

rest:
  server:
    address: http://localhost:8884/
  na:
    address: http://localhost:8888
  rekvirent:
    address: http://localhost:8889
  utleverer:
    address: http://localhost:8890

use:
  jwk: true