/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir;

import java.util.HashSet;

/**
 * Representing a Server Variable for server URL template substitution.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class ServerVariable {
    public String description;
    public String defaultValue;
    public HashSet<String> enumValues = null;

    /**
     * @param description A description for the server variable.
     * @param defaultValue The default value to use for substitution.
     * @param enumValues An enumeration of string values to be used if the substitution options are from a limited set.
     */
    public ServerVariable(String description, String defaultValue, HashSet<String> enumValues) {
        this.description = description;
        this.defaultValue = defaultValue;
        this.enumValues = enumValues;
    }
}
