/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.ActivityDefinitionAllOfExtensionOneOf1ValueReference;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * ActivityDefinitionAllOfExtensionOneOf1
 */
@JsonPropertyOrder({
  ActivityDefinitionAllOfExtensionOneOf1.JSON_PROPERTY_URL,
  ActivityDefinitionAllOfExtensionOneOf1.JSON_PROPERTY_VALUE_REFERENCE
})
@JsonTypeName("ActivityDefinition_allOf_extension_oneOf_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class ActivityDefinitionAllOfExtensionOneOf1 {
  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_VALUE_REFERENCE = "valueReference";
  @jakarta.annotation.Nullable
  private ActivityDefinitionAllOfExtensionOneOf1ValueReference valueReference;

  public ActivityDefinitionAllOfExtensionOneOf1() { 
  }

  public ActivityDefinitionAllOfExtensionOneOf1 url(@jakarta.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }


  public ActivityDefinitionAllOfExtensionOneOf1 valueReference(@jakarta.annotation.Nullable ActivityDefinitionAllOfExtensionOneOf1ValueReference valueReference) {
    this.valueReference = valueReference;
    return this;
  }

  /**
   * Get valueReference
   * @return valueReference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityDefinitionAllOfExtensionOneOf1ValueReference getValueReference() {
    return valueReference;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueReference(@jakarta.annotation.Nullable ActivityDefinitionAllOfExtensionOneOf1ValueReference valueReference) {
    this.valueReference = valueReference;
  }


  /**
   * Return true if this ActivityDefinition_allOf_extension_oneOf_1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityDefinitionAllOfExtensionOneOf1 activityDefinitionAllOfExtensionOneOf1 = (ActivityDefinitionAllOfExtensionOneOf1) o;
    return Objects.equals(this.url, activityDefinitionAllOfExtensionOneOf1.url) &&
        Objects.equals(this.valueReference, activityDefinitionAllOfExtensionOneOf1.valueReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, valueReference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityDefinitionAllOfExtensionOneOf1 {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    valueReference: ").append(toIndentedString(valueReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

