/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeSystemAllOfDesignation;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeSystemAllOfProperty1;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * CodeSystemAllOfConcept
 */
@JsonPropertyOrder({
  CodeSystemAllOfConcept.JSON_PROPERTY_CODE,
  CodeSystemAllOfConcept.JSON_PROPERTY_DISPLAY,
  CodeSystemAllOfConcept.JSON_PROPERTY_DESIGNATION,
  CodeSystemAllOfConcept.JSON_PROPERTY_PROPERTY
})
@JsonTypeName("CodeSystem_allOf_concept")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class CodeSystemAllOfConcept {
  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nonnull
  private String code;

  public static final String JSON_PROPERTY_DISPLAY = "display";
  @jakarta.annotation.Nullable
  private String display;

  public static final String JSON_PROPERTY_DESIGNATION = "designation";
  @jakarta.annotation.Nullable
  private CodeSystemAllOfDesignation designation;

  public static final String JSON_PROPERTY_PROPERTY = "property";
  @jakarta.annotation.Nullable
  private CodeSystemAllOfProperty1 property;

  public CodeSystemAllOfConcept() { 
  }

  public CodeSystemAllOfConcept code(@jakarta.annotation.Nonnull String code) {
    this.code = code;
    return this;
  }

  /**
   * SAFEST code. A merge of RMS identifier and DMP code
   * @return code
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@jakarta.annotation.Nonnull String code) {
    this.code = code;
  }


  public CodeSystemAllOfConcept display(@jakarta.annotation.Nullable String display) {
    this.display = display;
    return this;
  }

  /**
   * Term, english
   * @return display
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplay() {
    return display;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplay(@jakarta.annotation.Nullable String display) {
    this.display = display;
  }


  public CodeSystemAllOfConcept designation(@jakarta.annotation.Nullable CodeSystemAllOfDesignation designation) {
    this.designation = designation;
    return this;
  }

  /**
   * Get designation
   * @return designation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESIGNATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CodeSystemAllOfDesignation getDesignation() {
    return designation;
  }


  @JsonProperty(JSON_PROPERTY_DESIGNATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDesignation(@jakarta.annotation.Nullable CodeSystemAllOfDesignation designation) {
    this.designation = designation;
  }


  public CodeSystemAllOfConcept property(@jakarta.annotation.Nullable CodeSystemAllOfProperty1 property) {
    this.property = property;
    return this;
  }

  /**
   * Get property
   * @return property
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CodeSystemAllOfProperty1 getProperty() {
    return property;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperty(@jakarta.annotation.Nullable CodeSystemAllOfProperty1 property) {
    this.property = property;
  }


  /**
   * Return true if this CodeSystem_allOf_concept object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeSystemAllOfConcept codeSystemAllOfConcept = (CodeSystemAllOfConcept) o;
    return Objects.equals(this.code, codeSystemAllOfConcept.code) &&
        Objects.equals(this.display, codeSystemAllOfConcept.display) &&
        Objects.equals(this.designation, codeSystemAllOfConcept.designation) &&
        Objects.equals(this.property, codeSystemAllOfConcept.property);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, display, designation, property);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeSystemAllOfConcept {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    designation: ").append(toIndentedString(designation)).append("\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

