/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Coding;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * A CodeableConcept represents a value that is usually supplied by providing a reference to one or more terminologies or ontologies but may also be defined by the provision of text.
 */
@JsonPropertyOrder({
  CodeableConcept.JSON_PROPERTY_CODING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class CodeableConcept {
  public static final String JSON_PROPERTY_CODING = "coding";
  @jakarta.annotation.Nullable
  private List<Coding> coding = new ArrayList<>();

  public CodeableConcept() { 
  }

  public CodeableConcept coding(@jakarta.annotation.Nullable List<Coding> coding) {
    this.coding = coding;
    return this;
  }

  public CodeableConcept addCodingItem(Coding codingItem) {
    if (this.coding == null) {
      this.coding = new ArrayList<>();
    }
    this.coding.add(codingItem);
    return this;
  }

  /**
   * Code defined by a terminology system
   * @return coding
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Coding> getCoding() {
    return coding;
  }


  @JsonProperty(JSON_PROPERTY_CODING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoding(@jakarta.annotation.Nullable List<Coding> coding) {
    this.coding = coding;
  }


  /**
   * Return true if this CodeableConcept object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeableConcept codeableConcept = (CodeableConcept) o;
    return Objects.equals(this.coding, codeableConcept.coding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coding);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeableConcept {\n");
    sb.append("    coding: ").append(toIndentedString(coding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

