/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeSystemAllOfProperty1ValueCoding;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Properties/attributes about each code system element
 */
@JsonPropertyOrder({
  CodeSystemAllOfProperty1.JSON_PROPERTY_CODE,
  CodeSystemAllOfProperty1.JSON_PROPERTY_VALUE_CODING
})
@JsonTypeName("CodeSystem_allOf_property_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class CodeSystemAllOfProperty1 {
  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nonnull
  private String code;

  public static final String JSON_PROPERTY_VALUE_CODING = "valueCoding";
  @jakarta.annotation.Nonnull
  private CodeSystemAllOfProperty1ValueCoding valueCoding;

  public CodeSystemAllOfProperty1() { 
  }

  public CodeSystemAllOfProperty1 code(@jakarta.annotation.Nonnull String code) {
    this.code = code;
    return this;
  }

  /**
   * For all code elements there is a list of properties. This list contains, for example; term id and status from SPOR.
   * @return code
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@jakarta.annotation.Nonnull String code) {
    this.code = code;
  }


  public CodeSystemAllOfProperty1 valueCoding(@jakarta.annotation.Nonnull CodeSystemAllOfProperty1ValueCoding valueCoding) {
    this.valueCoding = valueCoding;
    return this;
  }

  /**
   * Get valueCoding
   * @return valueCoding
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUE_CODING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CodeSystemAllOfProperty1ValueCoding getValueCoding() {
    return valueCoding;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_CODING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValueCoding(@jakarta.annotation.Nonnull CodeSystemAllOfProperty1ValueCoding valueCoding) {
    this.valueCoding = valueCoding;
  }


  /**
   * Return true if this CodeSystem_allOf_property_1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeSystemAllOfProperty1 codeSystemAllOfProperty1 = (CodeSystemAllOfProperty1) o;
    return Objects.equals(this.code, codeSystemAllOfProperty1.code) &&
        Objects.equals(this.valueCoding, codeSystemAllOfProperty1.valueCoding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, valueCoding);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeSystemAllOfProperty1 {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    valueCoding: ").append(toIndentedString(valueCoding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

