/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.BasicAllOfCode;
import io.github.mjhaugsdal.eresept.fest.fhir.model.BasicAllOfExtension;
import io.github.mjhaugsdal.eresept.fest.fhir.model.BasicAllOfIdentifier;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Link;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductAllOfMeta;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * GetBasicIdHistory200Response
 */
@JsonPropertyOrder({
  GetBasicIdHistory200Response.JSON_PROPERTY_RESOURCE_TYPE,
  GetBasicIdHistory200Response.JSON_PROPERTY_ID,
  GetBasicIdHistory200Response.JSON_PROPERTY_META,
  GetBasicIdHistory200Response.JSON_PROPERTY_EXTENSION,
  GetBasicIdHistory200Response.JSON_PROPERTY_IDENTIFIER,
  GetBasicIdHistory200Response.JSON_PROPERTY_CODE,
  GetBasicIdHistory200Response.JSON_PROPERTY_TYPE,
  GetBasicIdHistory200Response.JSON_PROPERTY_LINK
})
@JsonTypeName("get_basic_id__history_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class GetBasicIdHistory200Response {
  /**
   * The resource type
   */
  public enum ResourceTypeEnum {
    BASIC(String.valueOf("Basic"));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @jakarta.annotation.Nullable
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_META = "meta";
  @jakarta.annotation.Nullable
  private MedicinalProductAllOfMeta meta;

  public static final String JSON_PROPERTY_EXTENSION = "extension";
  @jakarta.annotation.Nullable
  private List<BasicAllOfExtension> extension = new ArrayList<>();

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nullable
  private BasicAllOfIdentifier identifier;

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nonnull
  private BasicAllOfCode code;

  /**
   * The bundle type
   */
  public enum TypeEnum {
    HISTORY(String.valueOf("history"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_LINK = "link";
  @jakarta.annotation.Nullable
  private List<Link> link = new ArrayList<>();

  public GetBasicIdHistory200Response() { 
  }

  @JsonCreator
  public GetBasicIdHistory200Response(
    @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE) ResourceTypeEnum resourceType, 
    @JsonProperty(JSON_PROPERTY_ID) String id
  ) {
    this();
    this.resourceType = resourceType;
    this.id = id;
  }

  /**
   * The resource type
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }




  /**
   * Id of the resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }




  public GetBasicIdHistory200Response meta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductAllOfMeta getMeta() {
    return meta;
  }


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
  }


  public GetBasicIdHistory200Response extension(@jakarta.annotation.Nullable List<BasicAllOfExtension> extension) {
    this.extension = extension;
    return this;
  }

  public GetBasicIdHistory200Response addExtensionItem(BasicAllOfExtension extensionItem) {
    if (this.extension == null) {
      this.extension = new ArrayList<>();
    }
    this.extension.add(extensionItem);
    return this;
  }

  /**
   * Extensions of the resource
   * @return extension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BasicAllOfExtension> getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(@jakarta.annotation.Nullable List<BasicAllOfExtension> extension) {
    this.extension = extension;
  }


  public GetBasicIdHistory200Response identifier(@jakarta.annotation.Nullable BasicAllOfIdentifier identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BasicAllOfIdentifier getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifier(@jakarta.annotation.Nullable BasicAllOfIdentifier identifier) {
    this.identifier = identifier;
  }


  public GetBasicIdHistory200Response code(@jakarta.annotation.Nonnull BasicAllOfCode code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BasicAllOfCode getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@jakarta.annotation.Nonnull BasicAllOfCode code) {
    this.code = code;
  }


  public GetBasicIdHistory200Response type(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The bundle type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public GetBasicIdHistory200Response link(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
    return this;
  }

  public GetBasicIdHistory200Response addLinkItem(Link linkItem) {
    if (this.link == null) {
      this.link = new ArrayList<>();
    }
    this.link.add(linkItem);
    return this;
  }

  /**
   * Objects for pagination
   * @return link
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Link> getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
  }


  /**
   * Return true if this get_basic_id__history_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBasicIdHistory200Response getBasicIdHistory200Response = (GetBasicIdHistory200Response) o;
    return Objects.equals(this.resourceType, getBasicIdHistory200Response.resourceType) &&
        Objects.equals(this.id, getBasicIdHistory200Response.id) &&
        Objects.equals(this.meta, getBasicIdHistory200Response.meta) &&
        Objects.equals(this.extension, getBasicIdHistory200Response.extension) &&
        Objects.equals(this.identifier, getBasicIdHistory200Response.identifier) &&
        Objects.equals(this.code, getBasicIdHistory200Response.code) &&
        Objects.equals(this.type, getBasicIdHistory200Response.type) &&
        Objects.equals(this.link, getBasicIdHistory200Response.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, id, meta, extension, identifier, code, type, link);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBasicIdHistory200Response {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

