/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeSystemAllOfConcept;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeSystemAllOfIdentifier;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeSystemAllOfProperty;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Link;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductAllOfMeta;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * GetCodesystemIdHistory200Response
 */
@JsonPropertyOrder({
  GetCodesystemIdHistory200Response.JSON_PROPERTY_RESOURCE_TYPE,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_ID,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_META,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_IDENTIFIER,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_NAME,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_STATUS,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_CONTENT,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_PROPERTY,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_CONCEPT,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_TYPE,
  GetCodesystemIdHistory200Response.JSON_PROPERTY_LINK
})
@JsonTypeName("get_codesystem_id__history_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class GetCodesystemIdHistory200Response {
  /**
   * The resource type
   */
  public enum ResourceTypeEnum {
    SUBSTANCE(String.valueOf("Substance"));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @jakarta.annotation.Nullable
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_META = "meta";
  @jakarta.annotation.Nullable
  private MedicinalProductAllOfMeta meta;

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nullable
  private CodeSystemAllOfIdentifier identifier;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  /**
   * Publication status for the code system, either «draft», «active», «retired». In this dataset, all value sets are published.
   */
  public enum StatusEnum {
    DRAFT(String.valueOf("draft")),
    
    ACTIVE(String.valueOf("active")),
    
    RETIRED(String.valueOf("retired"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  /**
   * Is eiter «not-present», «example», «fragment», «complete» or «supplement».
   */
  public enum ContentEnum {
    NOT_PRESENT(String.valueOf("not-present")),
    
    EXAMPLE(String.valueOf("example")),
    
    FRAGMENT(String.valueOf("fragment")),
    
    COMPLETE(String.valueOf("complete")),
    
    SUPPLEMENT(String.valueOf("supplement"));

    private String value;

    ContentEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ContentEnum fromValue(String value) {
      for (ContentEnum b : ContentEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONTENT = "content";
  @jakarta.annotation.Nonnull
  private ContentEnum content;

  public static final String JSON_PROPERTY_PROPERTY = "property";
  @jakarta.annotation.Nullable
  private List<CodeSystemAllOfProperty> property = new ArrayList<>();

  public static final String JSON_PROPERTY_CONCEPT = "concept";
  @jakarta.annotation.Nullable
  private List<CodeSystemAllOfConcept> concept = new ArrayList<>();

  /**
   * The bundle type
   */
  public enum TypeEnum {
    HISTORY(String.valueOf("history"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_LINK = "link";
  @jakarta.annotation.Nullable
  private List<Link> link = new ArrayList<>();

  public GetCodesystemIdHistory200Response() { 
  }

  @JsonCreator
  public GetCodesystemIdHistory200Response(
    @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE) ResourceTypeEnum resourceType, 
    @JsonProperty(JSON_PROPERTY_ID) String id
  ) {
    this();
    this.resourceType = resourceType;
    this.id = id;
  }

  /**
   * The resource type
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }




  /**
   * Id of the resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }




  public GetCodesystemIdHistory200Response meta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductAllOfMeta getMeta() {
    return meta;
  }


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
  }


  public GetCodesystemIdHistory200Response identifier(@jakarta.annotation.Nullable CodeSystemAllOfIdentifier identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CodeSystemAllOfIdentifier getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifier(@jakarta.annotation.Nullable CodeSystemAllOfIdentifier identifier) {
    this.identifier = identifier;
  }


  public GetCodesystemIdHistory200Response name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the code system
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public GetCodesystemIdHistory200Response status(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Publication status for the code system, either «draft», «active», «retired». In this dataset, all value sets are published.
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public GetCodesystemIdHistory200Response content(@jakarta.annotation.Nonnull ContentEnum content) {
    this.content = content;
    return this;
  }

  /**
   * Is eiter «not-present», «example», «fragment», «complete» or «supplement».
   * @return content
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContentEnum getContent() {
    return content;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@jakarta.annotation.Nonnull ContentEnum content) {
    this.content = content;
  }


  public GetCodesystemIdHistory200Response property(@jakarta.annotation.Nullable List<CodeSystemAllOfProperty> property) {
    this.property = property;
    return this;
  }

  public GetCodesystemIdHistory200Response addPropertyItem(CodeSystemAllOfProperty propertyItem) {
    if (this.property == null) {
      this.property = new ArrayList<>();
    }
    this.property.add(propertyItem);
    return this;
  }

  /**
   * Properties/attributes which can be available on code system elements
   * @return property
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CodeSystemAllOfProperty> getProperty() {
    return property;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperty(@jakarta.annotation.Nullable List<CodeSystemAllOfProperty> property) {
    this.property = property;
  }


  public GetCodesystemIdHistory200Response concept(@jakarta.annotation.Nullable List<CodeSystemAllOfConcept> concept) {
    this.concept = concept;
    return this;
  }

  public GetCodesystemIdHistory200Response addConceptItem(CodeSystemAllOfConcept conceptItem) {
    if (this.concept == null) {
      this.concept = new ArrayList<>();
    }
    this.concept.add(conceptItem);
    return this;
  }

  /**
   * Code system elements
   * @return concept
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONCEPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CodeSystemAllOfConcept> getConcept() {
    return concept;
  }


  @JsonProperty(JSON_PROPERTY_CONCEPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConcept(@jakarta.annotation.Nullable List<CodeSystemAllOfConcept> concept) {
    this.concept = concept;
  }


  public GetCodesystemIdHistory200Response type(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The bundle type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public GetCodesystemIdHistory200Response link(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
    return this;
  }

  public GetCodesystemIdHistory200Response addLinkItem(Link linkItem) {
    if (this.link == null) {
      this.link = new ArrayList<>();
    }
    this.link.add(linkItem);
    return this;
  }

  /**
   * Objects for pagination
   * @return link
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Link> getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
  }


  /**
   * Return true if this get_codesystem_id__history_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCodesystemIdHistory200Response getCodesystemIdHistory200Response = (GetCodesystemIdHistory200Response) o;
    return Objects.equals(this.resourceType, getCodesystemIdHistory200Response.resourceType) &&
        Objects.equals(this.id, getCodesystemIdHistory200Response.id) &&
        Objects.equals(this.meta, getCodesystemIdHistory200Response.meta) &&
        Objects.equals(this.identifier, getCodesystemIdHistory200Response.identifier) &&
        Objects.equals(this.name, getCodesystemIdHistory200Response.name) &&
        Objects.equals(this.status, getCodesystemIdHistory200Response.status) &&
        Objects.equals(this.content, getCodesystemIdHistory200Response.content) &&
        Objects.equals(this.property, getCodesystemIdHistory200Response.property) &&
        Objects.equals(this.concept, getCodesystemIdHistory200Response.concept) &&
        Objects.equals(this.type, getCodesystemIdHistory200Response.type) &&
        Objects.equals(this.link, getCodesystemIdHistory200Response.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, id, meta, identifier, name, status, content, property, concept, type, link);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCodesystemIdHistory200Response {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("    concept: ").append(toIndentedString(concept)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

