/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Link;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductAllOfMeta;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPharmaceuticalAllOfAdministrableDoseForm;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPharmaceuticalAllOfExtension;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPharmaceuticalAllOfIdentifier;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPharmaceuticalAllOfRouteOfAdministration;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPharmaceuticalAllOfUnitOfPresentation;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Reference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * GetMedicinalproductpharmaceuticalIdHistory200Response
 */
@JsonPropertyOrder({
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_RESOURCE_TYPE,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_ID,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_META,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_EXTENSION,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_IDENTIFIER,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_ADMINISTRABLE_DOSE_FORM,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_UNIT_OF_PRESENTATION,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_ROUTE_OF_ADMINISTRATION,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_INGREDIENT,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_TYPE,
  GetMedicinalproductpharmaceuticalIdHistory200Response.JSON_PROPERTY_LINK
})
@JsonTypeName("get_medicinalproductpharmaceutical_id__history_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class GetMedicinalproductpharmaceuticalIdHistory200Response {
  /**
   * The resource type
   */
  public enum ResourceTypeEnum {
    MEDICINAL_PRODUCT_PHARMACEUTICAL(String.valueOf("MedicinalProductPharmaceutical"));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @jakarta.annotation.Nullable
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_META = "meta";
  @jakarta.annotation.Nullable
  private MedicinalProductAllOfMeta meta;

  public static final String JSON_PROPERTY_EXTENSION = "extension";
  @jakarta.annotation.Nullable
  private List<MedicinalProductPharmaceuticalAllOfExtension> extension = new ArrayList<>();

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nullable
  private MedicinalProductPharmaceuticalAllOfIdentifier identifier;

  public static final String JSON_PROPERTY_ADMINISTRABLE_DOSE_FORM = "administrableDoseForm";
  @jakarta.annotation.Nullable
  private MedicinalProductPharmaceuticalAllOfAdministrableDoseForm administrableDoseForm;

  public static final String JSON_PROPERTY_UNIT_OF_PRESENTATION = "unitOfPresentation";
  @jakarta.annotation.Nullable
  private MedicinalProductPharmaceuticalAllOfUnitOfPresentation unitOfPresentation;

  public static final String JSON_PROPERTY_ROUTE_OF_ADMINISTRATION = "routeOfAdministration";
  @jakarta.annotation.Nonnull
  private MedicinalProductPharmaceuticalAllOfRouteOfAdministration routeOfAdministration;

  public static final String JSON_PROPERTY_INGREDIENT = "ingredient";
  @jakarta.annotation.Nullable
  private List<Reference> ingredient = new ArrayList<>();

  /**
   * The bundle type
   */
  public enum TypeEnum {
    HISTORY(String.valueOf("history"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_LINK = "link";
  @jakarta.annotation.Nullable
  private List<Link> link = new ArrayList<>();

  public GetMedicinalproductpharmaceuticalIdHistory200Response() { 
  }

  @JsonCreator
  public GetMedicinalproductpharmaceuticalIdHistory200Response(
    @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE) ResourceTypeEnum resourceType, 
    @JsonProperty(JSON_PROPERTY_ID) String id
  ) {
    this();
    this.resourceType = resourceType;
    this.id = id;
  }

  /**
   * The resource type
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }




  /**
   * Id of the resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }




  public GetMedicinalproductpharmaceuticalIdHistory200Response meta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductAllOfMeta getMeta() {
    return meta;
  }


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
  }


  public GetMedicinalproductpharmaceuticalIdHistory200Response extension(@jakarta.annotation.Nullable List<MedicinalProductPharmaceuticalAllOfExtension> extension) {
    this.extension = extension;
    return this;
  }

  public GetMedicinalproductpharmaceuticalIdHistory200Response addExtensionItem(MedicinalProductPharmaceuticalAllOfExtension extensionItem) {
    if (this.extension == null) {
      this.extension = new ArrayList<>();
    }
    this.extension.add(extensionItem);
    return this;
  }

  /**
   * Extensions for the nutrition product. Since Nutrition product does not exist in FHIR R4 and Basic is used as a substitute, all properties has to be represented as extensions
   * @return extension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MedicinalProductPharmaceuticalAllOfExtension> getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(@jakarta.annotation.Nullable List<MedicinalProductPharmaceuticalAllOfExtension> extension) {
    this.extension = extension;
  }


  public GetMedicinalproductpharmaceuticalIdHistory200Response identifier(@jakarta.annotation.Nullable MedicinalProductPharmaceuticalAllOfIdentifier identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductPharmaceuticalAllOfIdentifier getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifier(@jakarta.annotation.Nullable MedicinalProductPharmaceuticalAllOfIdentifier identifier) {
    this.identifier = identifier;
  }


  public GetMedicinalproductpharmaceuticalIdHistory200Response administrableDoseForm(@jakarta.annotation.Nullable MedicinalProductPharmaceuticalAllOfAdministrableDoseForm administrableDoseForm) {
    this.administrableDoseForm = administrableDoseForm;
    return this;
  }

  /**
   * Get administrableDoseForm
   * @return administrableDoseForm
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADMINISTRABLE_DOSE_FORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductPharmaceuticalAllOfAdministrableDoseForm getAdministrableDoseForm() {
    return administrableDoseForm;
  }


  @JsonProperty(JSON_PROPERTY_ADMINISTRABLE_DOSE_FORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdministrableDoseForm(@jakarta.annotation.Nullable MedicinalProductPharmaceuticalAllOfAdministrableDoseForm administrableDoseForm) {
    this.administrableDoseForm = administrableDoseForm;
  }


  public GetMedicinalproductpharmaceuticalIdHistory200Response unitOfPresentation(@jakarta.annotation.Nullable MedicinalProductPharmaceuticalAllOfUnitOfPresentation unitOfPresentation) {
    this.unitOfPresentation = unitOfPresentation;
    return this;
  }

  /**
   * Get unitOfPresentation
   * @return unitOfPresentation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIT_OF_PRESENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductPharmaceuticalAllOfUnitOfPresentation getUnitOfPresentation() {
    return unitOfPresentation;
  }


  @JsonProperty(JSON_PROPERTY_UNIT_OF_PRESENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnitOfPresentation(@jakarta.annotation.Nullable MedicinalProductPharmaceuticalAllOfUnitOfPresentation unitOfPresentation) {
    this.unitOfPresentation = unitOfPresentation;
  }


  public GetMedicinalproductpharmaceuticalIdHistory200Response routeOfAdministration(@jakarta.annotation.Nonnull MedicinalProductPharmaceuticalAllOfRouteOfAdministration routeOfAdministration) {
    this.routeOfAdministration = routeOfAdministration;
    return this;
  }

  /**
   * Get routeOfAdministration
   * @return routeOfAdministration
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROUTE_OF_ADMINISTRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MedicinalProductPharmaceuticalAllOfRouteOfAdministration getRouteOfAdministration() {
    return routeOfAdministration;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_OF_ADMINISTRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteOfAdministration(@jakarta.annotation.Nonnull MedicinalProductPharmaceuticalAllOfRouteOfAdministration routeOfAdministration) {
    this.routeOfAdministration = routeOfAdministration;
  }


  public GetMedicinalproductpharmaceuticalIdHistory200Response ingredient(@jakarta.annotation.Nullable List<Reference> ingredient) {
    this.ingredient = ingredient;
    return this;
  }

  public GetMedicinalproductpharmaceuticalIdHistory200Response addIngredientItem(Reference ingredientItem) {
    if (this.ingredient == null) {
      this.ingredient = new ArrayList<>();
    }
    this.ingredient.add(ingredientItem);
    return this;
  }

  /**
   * Related Ingredient
   * @return ingredient
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INGREDIENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Reference> getIngredient() {
    return ingredient;
  }


  @JsonProperty(JSON_PROPERTY_INGREDIENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIngredient(@jakarta.annotation.Nullable List<Reference> ingredient) {
    this.ingredient = ingredient;
  }


  public GetMedicinalproductpharmaceuticalIdHistory200Response type(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The bundle type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public GetMedicinalproductpharmaceuticalIdHistory200Response link(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
    return this;
  }

  public GetMedicinalproductpharmaceuticalIdHistory200Response addLinkItem(Link linkItem) {
    if (this.link == null) {
      this.link = new ArrayList<>();
    }
    this.link.add(linkItem);
    return this;
  }

  /**
   * Objects for pagination
   * @return link
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Link> getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
  }


  /**
   * Return true if this get_medicinalproductpharmaceutical_id__history_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMedicinalproductpharmaceuticalIdHistory200Response getMedicinalproductpharmaceuticalIdHistory200Response = (GetMedicinalproductpharmaceuticalIdHistory200Response) o;
    return Objects.equals(this.resourceType, getMedicinalproductpharmaceuticalIdHistory200Response.resourceType) &&
        Objects.equals(this.id, getMedicinalproductpharmaceuticalIdHistory200Response.id) &&
        Objects.equals(this.meta, getMedicinalproductpharmaceuticalIdHistory200Response.meta) &&
        Objects.equals(this.extension, getMedicinalproductpharmaceuticalIdHistory200Response.extension) &&
        Objects.equals(this.identifier, getMedicinalproductpharmaceuticalIdHistory200Response.identifier) &&
        Objects.equals(this.administrableDoseForm, getMedicinalproductpharmaceuticalIdHistory200Response.administrableDoseForm) &&
        Objects.equals(this.unitOfPresentation, getMedicinalproductpharmaceuticalIdHistory200Response.unitOfPresentation) &&
        Objects.equals(this.routeOfAdministration, getMedicinalproductpharmaceuticalIdHistory200Response.routeOfAdministration) &&
        Objects.equals(this.ingredient, getMedicinalproductpharmaceuticalIdHistory200Response.ingredient) &&
        Objects.equals(this.type, getMedicinalproductpharmaceuticalIdHistory200Response.type) &&
        Objects.equals(this.link, getMedicinalproductpharmaceuticalIdHistory200Response.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, id, meta, extension, identifier, administrableDoseForm, unitOfPresentation, routeOfAdministration, ingredient, type, link);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMedicinalproductpharmaceuticalIdHistory200Response {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    administrableDoseForm: ").append(toIndentedString(administrableDoseForm)).append("\n");
    sb.append("    unitOfPresentation: ").append(toIndentedString(unitOfPresentation)).append("\n");
    sb.append("    routeOfAdministration: ").append(toIndentedString(routeOfAdministration)).append("\n");
    sb.append("    ingredient: ").append(toIndentedString(ingredient)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

