/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeableConcept;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Link;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductAllOfExtension;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductAllOfLegalStatusOfSupply;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductAllOfMeta;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Name;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Reference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * GetMedicinalproductIdHistory200Response
 */
@JsonPropertyOrder({
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_RESOURCE_TYPE,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_ID,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_META,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_EXTENSION,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_IDENTIFIER,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_LEGAL_STATUS_OF_SUPPLY,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_PRODUCT_CLASSIFICATION,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_PACKAGED_MEDICINAL_PRODUCT,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_NAME,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_TYPE,
  GetMedicinalproductIdHistory200Response.JSON_PROPERTY_LINK
})
@JsonTypeName("get_medicinalproduct_id__history_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class GetMedicinalproductIdHistory200Response {
  /**
   * The resource type
   */
  public enum ResourceTypeEnum {
    MEDICINAL_PRODUCT(String.valueOf("MedicinalProduct"));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @jakarta.annotation.Nullable
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_META = "meta";
  @jakarta.annotation.Nullable
  private MedicinalProductAllOfMeta meta;

  public static final String JSON_PROPERTY_EXTENSION = "extension";
  @jakarta.annotation.Nullable
  private List<MedicinalProductAllOfExtension> extension = new ArrayList<>();

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nullable
  private List<Object> identifier = new ArrayList<>();

  public static final String JSON_PROPERTY_LEGAL_STATUS_OF_SUPPLY = "legalStatusOfSupply";
  @jakarta.annotation.Nullable
  private MedicinalProductAllOfLegalStatusOfSupply legalStatusOfSupply;

  public static final String JSON_PROPERTY_PRODUCT_CLASSIFICATION = "productClassification";
  @jakarta.annotation.Nullable
  private List<CodeableConcept> productClassification = new ArrayList<>();

  public static final String JSON_PROPERTY_PACKAGED_MEDICINAL_PRODUCT = "packagedMedicinalProduct";
  @jakarta.annotation.Nullable
  private List<Reference> packagedMedicinalProduct = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private List<Name> name = new ArrayList<>();

  /**
   * The bundle type
   */
  public enum TypeEnum {
    HISTORY(String.valueOf("history"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_LINK = "link";
  @jakarta.annotation.Nullable
  private List<Link> link = new ArrayList<>();

  public GetMedicinalproductIdHistory200Response() { 
  }

  @JsonCreator
  public GetMedicinalproductIdHistory200Response(
    @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE) ResourceTypeEnum resourceType, 
    @JsonProperty(JSON_PROPERTY_ID) String id
  ) {
    this();
    this.resourceType = resourceType;
    this.id = id;
  }

  /**
   * The resource type
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }




  /**
   * Id of the resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }




  public GetMedicinalproductIdHistory200Response meta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductAllOfMeta getMeta() {
    return meta;
  }


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
  }


  public GetMedicinalproductIdHistory200Response extension(@jakarta.annotation.Nullable List<MedicinalProductAllOfExtension> extension) {
    this.extension = extension;
    return this;
  }

  public GetMedicinalproductIdHistory200Response addExtensionItem(MedicinalProductAllOfExtension extensionItem) {
    if (this.extension == null) {
      this.extension = new ArrayList<>();
    }
    this.extension.add(extensionItem);
    return this;
  }

  /**
   * Extensions for the package.
   * @return extension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MedicinalProductAllOfExtension> getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(@jakarta.annotation.Nullable List<MedicinalProductAllOfExtension> extension) {
    this.extension = extension;
  }


  public GetMedicinalproductIdHistory200Response identifier(@jakarta.annotation.Nullable List<Object> identifier) {
    this.identifier = identifier;
    return this;
  }

  public GetMedicinalproductIdHistory200Response addIdentifierItem(Object identifierItem) {
    if (this.identifier == null) {
      this.identifier = new ArrayList<>();
    }
    this.identifier.add(identifierItem);
    return this;
  }

  /**
   * Business identifier for this product
   * @return identifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifier(@jakarta.annotation.Nullable List<Object> identifier) {
    this.identifier = identifier;
  }


  public GetMedicinalproductIdHistory200Response legalStatusOfSupply(@jakarta.annotation.Nullable MedicinalProductAllOfLegalStatusOfSupply legalStatusOfSupply) {
    this.legalStatusOfSupply = legalStatusOfSupply;
    return this;
  }

  /**
   * Get legalStatusOfSupply
   * @return legalStatusOfSupply
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGAL_STATUS_OF_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductAllOfLegalStatusOfSupply getLegalStatusOfSupply() {
    return legalStatusOfSupply;
  }


  @JsonProperty(JSON_PROPERTY_LEGAL_STATUS_OF_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegalStatusOfSupply(@jakarta.annotation.Nullable MedicinalProductAllOfLegalStatusOfSupply legalStatusOfSupply) {
    this.legalStatusOfSupply = legalStatusOfSupply;
  }


  public GetMedicinalproductIdHistory200Response productClassification(@jakarta.annotation.Nullable List<CodeableConcept> productClassification) {
    this.productClassification = productClassification;
    return this;
  }

  public GetMedicinalproductIdHistory200Response addProductClassificationItem(CodeableConcept productClassificationItem) {
    if (this.productClassification == null) {
      this.productClassification = new ArrayList<>();
    }
    this.productClassification.add(productClassificationItem);
    return this;
  }

  /**
   * Allows the product to be classified by various systems
   * @return productClassification
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT_CLASSIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CodeableConcept> getProductClassification() {
    return productClassification;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_CLASSIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductClassification(@jakarta.annotation.Nullable List<CodeableConcept> productClassification) {
    this.productClassification = productClassification;
  }


  public GetMedicinalproductIdHistory200Response packagedMedicinalProduct(@jakarta.annotation.Nullable List<Reference> packagedMedicinalProduct) {
    this.packagedMedicinalProduct = packagedMedicinalProduct;
    return this;
  }

  public GetMedicinalproductIdHistory200Response addPackagedMedicinalProductItem(Reference packagedMedicinalProductItem) {
    if (this.packagedMedicinalProduct == null) {
      this.packagedMedicinalProduct = new ArrayList<>();
    }
    this.packagedMedicinalProduct.add(packagedMedicinalProductItem);
    return this;
  }

  /**
   * Package type for the product
   * @return packagedMedicinalProduct
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PACKAGED_MEDICINAL_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Reference> getPackagedMedicinalProduct() {
    return packagedMedicinalProduct;
  }


  @JsonProperty(JSON_PROPERTY_PACKAGED_MEDICINAL_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackagedMedicinalProduct(@jakarta.annotation.Nullable List<Reference> packagedMedicinalProduct) {
    this.packagedMedicinalProduct = packagedMedicinalProduct;
  }


  public GetMedicinalproductIdHistory200Response name(@jakarta.annotation.Nullable List<Name> name) {
    this.name = name;
    return this;
  }

  public GetMedicinalproductIdHistory200Response addNameItem(Name nameItem) {
    if (this.name == null) {
      this.name = new ArrayList<>();
    }
    this.name.add(nameItem);
    return this;
  }

  /**
   * The product&#39;s name, including full name and possibly coded parts
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Name> getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable List<Name> name) {
    this.name = name;
  }


  public GetMedicinalproductIdHistory200Response type(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The bundle type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public GetMedicinalproductIdHistory200Response link(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
    return this;
  }

  public GetMedicinalproductIdHistory200Response addLinkItem(Link linkItem) {
    if (this.link == null) {
      this.link = new ArrayList<>();
    }
    this.link.add(linkItem);
    return this;
  }

  /**
   * Objects for pagination
   * @return link
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Link> getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
  }


  /**
   * Return true if this get_medicinalproduct_id__history_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMedicinalproductIdHistory200Response getMedicinalproductIdHistory200Response = (GetMedicinalproductIdHistory200Response) o;
    return Objects.equals(this.resourceType, getMedicinalproductIdHistory200Response.resourceType) &&
        Objects.equals(this.id, getMedicinalproductIdHistory200Response.id) &&
        Objects.equals(this.meta, getMedicinalproductIdHistory200Response.meta) &&
        Objects.equals(this.extension, getMedicinalproductIdHistory200Response.extension) &&
        Objects.equals(this.identifier, getMedicinalproductIdHistory200Response.identifier) &&
        Objects.equals(this.legalStatusOfSupply, getMedicinalproductIdHistory200Response.legalStatusOfSupply) &&
        Objects.equals(this.productClassification, getMedicinalproductIdHistory200Response.productClassification) &&
        Objects.equals(this.packagedMedicinalProduct, getMedicinalproductIdHistory200Response.packagedMedicinalProduct) &&
        Objects.equals(this.name, getMedicinalproductIdHistory200Response.name) &&
        Objects.equals(this.type, getMedicinalproductIdHistory200Response.type) &&
        Objects.equals(this.link, getMedicinalproductIdHistory200Response.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, id, meta, extension, identifier, legalStatusOfSupply, productClassification, packagedMedicinalProduct, name, type, link);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMedicinalproductIdHistory200Response {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    legalStatusOfSupply: ").append(toIndentedString(legalStatusOfSupply)).append("\n");
    sb.append("    productClassification: ").append(toIndentedString(productClassification)).append("\n");
    sb.append("    packagedMedicinalProduct: ").append(toIndentedString(packagedMedicinalProduct)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

