/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MarketingStatus;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductAllOfMeta;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPackagedAllOfExtension;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPackagedAllOfIdentifier;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPackagedAllOfLegalStatusOfSupply;
import io.github.mjhaugsdal.eresept.fest.fhir.model.ModelPackage;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Reference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * MedicinalProductPackaged
 */
@JsonPropertyOrder({
  MedicinalProductPackaged.JSON_PROPERTY_RESOURCE_TYPE,
  MedicinalProductPackaged.JSON_PROPERTY_ID,
  MedicinalProductPackaged.JSON_PROPERTY_META,
  MedicinalProductPackaged.JSON_PROPERTY_EXTENSION,
  MedicinalProductPackaged.JSON_PROPERTY_IDENTIFIER,
  MedicinalProductPackaged.JSON_PROPERTY_LEGAL_STATUS_OF_SUPPLY,
  MedicinalProductPackaged.JSON_PROPERTY_MARKETING_STATUS,
  MedicinalProductPackaged.JSON_PROPERTY_DESCRIPTION,
  MedicinalProductPackaged.JSON_PROPERTY_SUBJECT,
  MedicinalProductPackaged.JSON_PROPERTY_PACKAGE_ITEM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class MedicinalProductPackaged {
  /**
   * The resource type
   */
  public enum ResourceTypeEnum {
    MEDICINAL_PRODUCT_PACKAGED(String.valueOf("MedicinalProductPackaged"));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @jakarta.annotation.Nullable
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_META = "meta";
  @jakarta.annotation.Nullable
  private MedicinalProductAllOfMeta meta;

  public static final String JSON_PROPERTY_EXTENSION = "extension";
  @jakarta.annotation.Nullable
  private List<MedicinalProductPackagedAllOfExtension> extension = new ArrayList<>();

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nonnull
  private List<MedicinalProductPackagedAllOfIdentifier> identifier = new ArrayList<>();

  public static final String JSON_PROPERTY_LEGAL_STATUS_OF_SUPPLY = "legalStatusOfSupply";
  @jakarta.annotation.Nullable
  private MedicinalProductPackagedAllOfLegalStatusOfSupply legalStatusOfSupply;

  public static final String JSON_PROPERTY_MARKETING_STATUS = "marketingStatus";
  @jakarta.annotation.Nullable
  private List<MarketingStatus> marketingStatus = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @jakarta.annotation.Nonnull
  private List<Reference> subject = new ArrayList<>();

  public static final String JSON_PROPERTY_PACKAGE_ITEM = "packageItem";
  @jakarta.annotation.Nullable
  private List<ModelPackage> packageItem = new ArrayList<>();

  public MedicinalProductPackaged() { 
  }

  @JsonCreator
  public MedicinalProductPackaged(
    @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE) ResourceTypeEnum resourceType, 
    @JsonProperty(JSON_PROPERTY_ID) String id
  ) {
    this();
    this.resourceType = resourceType;
    this.id = id;
  }

  /**
   * The resource type
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }




  /**
   * Id of the resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }




  public MedicinalProductPackaged meta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductAllOfMeta getMeta() {
    return meta;
  }


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
  }


  public MedicinalProductPackaged extension(@jakarta.annotation.Nullable List<MedicinalProductPackagedAllOfExtension> extension) {
    this.extension = extension;
    return this;
  }

  public MedicinalProductPackaged addExtensionItem(MedicinalProductPackagedAllOfExtension extensionItem) {
    if (this.extension == null) {
      this.extension = new ArrayList<>();
    }
    this.extension.add(extensionItem);
    return this;
  }

  /**
   * Extensions for the package.
   * @return extension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MedicinalProductPackagedAllOfExtension> getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(@jakarta.annotation.Nullable List<MedicinalProductPackagedAllOfExtension> extension) {
    this.extension = extension;
  }


  public MedicinalProductPackaged identifier(@jakarta.annotation.Nonnull List<MedicinalProductPackagedAllOfIdentifier> identifier) {
    this.identifier = identifier;
    return this;
  }

  public MedicinalProductPackaged addIdentifierItem(MedicinalProductPackagedAllOfIdentifier identifierItem) {
    if (this.identifier == null) {
      this.identifier = new ArrayList<>();
    }
    this.identifier.add(identifierItem);
    return this;
  }

  /**
   * Business identifier for this product
   * @return identifier
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<MedicinalProductPackagedAllOfIdentifier> getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifier(@jakarta.annotation.Nonnull List<MedicinalProductPackagedAllOfIdentifier> identifier) {
    this.identifier = identifier;
  }


  public MedicinalProductPackaged legalStatusOfSupply(@jakarta.annotation.Nullable MedicinalProductPackagedAllOfLegalStatusOfSupply legalStatusOfSupply) {
    this.legalStatusOfSupply = legalStatusOfSupply;
    return this;
  }

  /**
   * Get legalStatusOfSupply
   * @return legalStatusOfSupply
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGAL_STATUS_OF_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductPackagedAllOfLegalStatusOfSupply getLegalStatusOfSupply() {
    return legalStatusOfSupply;
  }


  @JsonProperty(JSON_PROPERTY_LEGAL_STATUS_OF_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegalStatusOfSupply(@jakarta.annotation.Nullable MedicinalProductPackagedAllOfLegalStatusOfSupply legalStatusOfSupply) {
    this.legalStatusOfSupply = legalStatusOfSupply;
  }


  public MedicinalProductPackaged marketingStatus(@jakarta.annotation.Nullable List<MarketingStatus> marketingStatus) {
    this.marketingStatus = marketingStatus;
    return this;
  }

  public MedicinalProductPackaged addMarketingStatusItem(MarketingStatus marketingStatusItem) {
    if (this.marketingStatus == null) {
      this.marketingStatus = new ArrayList<>();
    }
    this.marketingStatus.add(marketingStatusItem);
    return this;
  }

  /**
   * MarketingStatus
   * @return marketingStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKETING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MarketingStatus> getMarketingStatus() {
    return marketingStatus;
  }


  @JsonProperty(JSON_PROPERTY_MARKETING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketingStatus(@jakarta.annotation.Nullable List<MarketingStatus> marketingStatus) {
    this.marketingStatus = marketingStatus;
  }


  public MedicinalProductPackaged description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Description of the package
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public MedicinalProductPackaged subject(@jakarta.annotation.Nonnull List<Reference> subject) {
    this.subject = subject;
    return this;
  }

  public MedicinalProductPackaged addSubjectItem(Reference subjectItem) {
    if (this.subject == null) {
      this.subject = new ArrayList<>();
    }
    this.subject.add(subjectItem);
    return this;
  }

  /**
   * Related Medicinal Product
   * @return subject
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Reference> getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@jakarta.annotation.Nonnull List<Reference> subject) {
    this.subject = subject;
  }


  public MedicinalProductPackaged packageItem(@jakarta.annotation.Nullable List<ModelPackage> packageItem) {
    this.packageItem = packageItem;
    return this;
  }

  public MedicinalProductPackaged addPackageItemItem(ModelPackage packageItemItem) {
    if (this.packageItem == null) {
      this.packageItem = new ArrayList<>();
    }
    this.packageItem.add(packageItemItem);
    return this;
  }

  /**
   * Top element in the package hierarchy
   * @return packageItem
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PACKAGE_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModelPackage> getPackageItem() {
    return packageItem;
  }


  @JsonProperty(JSON_PROPERTY_PACKAGE_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackageItem(@jakarta.annotation.Nullable List<ModelPackage> packageItem) {
    this.packageItem = packageItem;
  }


  /**
   * Return true if this MedicinalProductPackaged object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicinalProductPackaged medicinalProductPackaged = (MedicinalProductPackaged) o;
    return Objects.equals(this.resourceType, medicinalProductPackaged.resourceType) &&
        Objects.equals(this.id, medicinalProductPackaged.id) &&
        Objects.equals(this.meta, medicinalProductPackaged.meta) &&
        Objects.equals(this.extension, medicinalProductPackaged.extension) &&
        Objects.equals(this.identifier, medicinalProductPackaged.identifier) &&
        Objects.equals(this.legalStatusOfSupply, medicinalProductPackaged.legalStatusOfSupply) &&
        Objects.equals(this.marketingStatus, medicinalProductPackaged.marketingStatus) &&
        Objects.equals(this.description, medicinalProductPackaged.description) &&
        Objects.equals(this.subject, medicinalProductPackaged.subject) &&
        Objects.equals(this.packageItem, medicinalProductPackaged.packageItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, id, meta, extension, identifier, legalStatusOfSupply, marketingStatus, description, subject, packageItem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicinalProductPackaged {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    legalStatusOfSupply: ").append(toIndentedString(legalStatusOfSupply)).append("\n");
    sb.append("    marketingStatus: ").append(toIndentedString(marketingStatus)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    packageItem: ").append(toIndentedString(packageItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

