/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductAllOfMeta;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfIdentifier;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfRole;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfSubstance;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * MedicinalProductIngredient
 */
@JsonPropertyOrder({
  MedicinalProductIngredient.JSON_PROPERTY_RESOURCE_TYPE,
  MedicinalProductIngredient.JSON_PROPERTY_ID,
  MedicinalProductIngredient.JSON_PROPERTY_META,
  MedicinalProductIngredient.JSON_PROPERTY_IDENTIFIER,
  MedicinalProductIngredient.JSON_PROPERTY_ROLE,
  MedicinalProductIngredient.JSON_PROPERTY_SUBSTANCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class MedicinalProductIngredient {
  /**
   * The resource type
   */
  public enum ResourceTypeEnum {
    MEDICINAL_PRODUCT_INGREDIENT(String.valueOf("MedicinalProductIngredient"));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @jakarta.annotation.Nullable
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_META = "meta";
  @jakarta.annotation.Nullable
  private MedicinalProductAllOfMeta meta;

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nonnull
  private MedicinalProductIngredientAllOfIdentifier identifier;

  public static final String JSON_PROPERTY_ROLE = "role";
  @jakarta.annotation.Nonnull
  private MedicinalProductIngredientAllOfRole role;

  public static final String JSON_PROPERTY_SUBSTANCE = "substance";
  @jakarta.annotation.Nonnull
  private MedicinalProductIngredientAllOfSubstance substance;

  public MedicinalProductIngredient() { 
  }

  @JsonCreator
  public MedicinalProductIngredient(
    @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE) ResourceTypeEnum resourceType, 
    @JsonProperty(JSON_PROPERTY_ID) String id
  ) {
    this();
    this.resourceType = resourceType;
    this.id = id;
  }

  /**
   * The resource type
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }




  /**
   * Id of the resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }




  public MedicinalProductIngredient meta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductAllOfMeta getMeta() {
    return meta;
  }


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@jakarta.annotation.Nullable MedicinalProductAllOfMeta meta) {
    this.meta = meta;
  }


  public MedicinalProductIngredient identifier(@jakarta.annotation.Nonnull MedicinalProductIngredientAllOfIdentifier identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MedicinalProductIngredientAllOfIdentifier getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifier(@jakarta.annotation.Nonnull MedicinalProductIngredientAllOfIdentifier identifier) {
    this.identifier = identifier;
  }


  public MedicinalProductIngredient role(@jakarta.annotation.Nonnull MedicinalProductIngredientAllOfRole role) {
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MedicinalProductIngredientAllOfRole getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRole(@jakarta.annotation.Nonnull MedicinalProductIngredientAllOfRole role) {
    this.role = role;
  }


  public MedicinalProductIngredient substance(@jakarta.annotation.Nonnull MedicinalProductIngredientAllOfSubstance substance) {
    this.substance = substance;
    return this;
  }

  /**
   * Get substance
   * @return substance
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBSTANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MedicinalProductIngredientAllOfSubstance getSubstance() {
    return substance;
  }


  @JsonProperty(JSON_PROPERTY_SUBSTANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubstance(@jakarta.annotation.Nonnull MedicinalProductIngredientAllOfSubstance substance) {
    this.substance = substance;
  }


  /**
   * Return true if this MedicinalProductIngredient object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicinalProductIngredient medicinalProductIngredient = (MedicinalProductIngredient) o;
    return Objects.equals(this.resourceType, medicinalProductIngredient.resourceType) &&
        Objects.equals(this.id, medicinalProductIngredient.id) &&
        Objects.equals(this.meta, medicinalProductIngredient.meta) &&
        Objects.equals(this.identifier, medicinalProductIngredient.identifier) &&
        Objects.equals(this.role, medicinalProductIngredient.role) &&
        Objects.equals(this.substance, medicinalProductIngredient.substance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, id, meta, identifier, role, substance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicinalProductIngredient {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    substance: ").append(toIndentedString(substance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

