/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfSubstanceCode;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfSubstanceStrength;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Substance comprising the ingredient.
 */
@JsonPropertyOrder({
  MedicinalProductIngredientAllOfSubstance.JSON_PROPERTY_CODE,
  MedicinalProductIngredientAllOfSubstance.JSON_PROPERTY_STRENGTH
})
@JsonTypeName("MedicinalProductIngredient_allOf_substance")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class MedicinalProductIngredientAllOfSubstance {
  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nonnull
  private MedicinalProductIngredientAllOfSubstanceCode code;

  public static final String JSON_PROPERTY_STRENGTH = "strength";
  @jakarta.annotation.Nullable
  private List<MedicinalProductIngredientAllOfSubstanceStrength> strength = new ArrayList<>();

  public MedicinalProductIngredientAllOfSubstance() { 
  }

  public MedicinalProductIngredientAllOfSubstance code(@jakarta.annotation.Nonnull MedicinalProductIngredientAllOfSubstanceCode code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MedicinalProductIngredientAllOfSubstanceCode getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@jakarta.annotation.Nonnull MedicinalProductIngredientAllOfSubstanceCode code) {
    this.code = code;
  }


  public MedicinalProductIngredientAllOfSubstance strength(@jakarta.annotation.Nullable List<MedicinalProductIngredientAllOfSubstanceStrength> strength) {
    this.strength = strength;
    return this;
  }

  public MedicinalProductIngredientAllOfSubstance addStrengthItem(MedicinalProductIngredientAllOfSubstanceStrength strengthItem) {
    if (this.strength == null) {
      this.strength = new ArrayList<>();
    }
    this.strength.add(strengthItem);
    return this;
  }

  /**
   * Strength for the ingredient
   * @return strength
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MedicinalProductIngredientAllOfSubstanceStrength> getStrength() {
    return strength;
  }


  @JsonProperty(JSON_PROPERTY_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStrength(@jakarta.annotation.Nullable List<MedicinalProductIngredientAllOfSubstanceStrength> strength) {
    this.strength = strength;
  }


  /**
   * Return true if this MedicinalProductIngredient_allOf_substance object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicinalProductIngredientAllOfSubstance medicinalProductIngredientAllOfSubstance = (MedicinalProductIngredientAllOfSubstance) o;
    return Objects.equals(this.code, medicinalProductIngredientAllOfSubstance.code) &&
        Objects.equals(this.strength, medicinalProductIngredientAllOfSubstance.strength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, strength);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicinalProductIngredientAllOfSubstance {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    strength: ").append(toIndentedString(strength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

