/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.AuthorizedPharmaceuticalDoseForm;
import io.github.mjhaugsdal.eresept.fest.fhir.model.AbstractOpenApiSchema;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeableConcept;
import io.github.mjhaugsdal.eresept.fest.fhir.model.NutritionDoseForm;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
@JsonDeserialize(using=MedicinalProductAllOfExtension.MedicinalProductAllOfExtensionDeserializer.class)
@JsonSerialize(using = MedicinalProductAllOfExtension.MedicinalProductAllOfExtensionSerializer.class)
public class MedicinalProductAllOfExtension extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(MedicinalProductAllOfExtension.class.getName());

    public static class MedicinalProductAllOfExtensionSerializer extends StdSerializer<MedicinalProductAllOfExtension> {
        public MedicinalProductAllOfExtensionSerializer(Class<MedicinalProductAllOfExtension> t) {
            super(t);
        }

        public MedicinalProductAllOfExtensionSerializer() {
            this(null);
        }

        @Override
        public void serialize(MedicinalProductAllOfExtension value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class MedicinalProductAllOfExtensionDeserializer extends StdDeserializer<MedicinalProductAllOfExtension> {
        public MedicinalProductAllOfExtensionDeserializer() {
            this(MedicinalProductAllOfExtension.class);
        }

        public MedicinalProductAllOfExtensionDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public MedicinalProductAllOfExtension deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize AuthorizedPharmaceuticalDoseForm
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(AuthorizedPharmaceuticalDoseForm.class);
                MedicinalProductAllOfExtension ret = new MedicinalProductAllOfExtension();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'MedicinalProductAllOfExtension'", e);
            }

            // deserialize NutritionDoseForm
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(NutritionDoseForm.class);
                MedicinalProductAllOfExtension ret = new MedicinalProductAllOfExtension();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'MedicinalProductAllOfExtension'", e);
            }

            throw new IOException(String.format("Failed deserialization for MedicinalProductAllOfExtension: no match found"));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public MedicinalProductAllOfExtension getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "MedicinalProductAllOfExtension cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public MedicinalProductAllOfExtension() {
        super("anyOf", Boolean.FALSE);
    }

    public MedicinalProductAllOfExtension(AuthorizedPharmaceuticalDoseForm o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public MedicinalProductAllOfExtension(NutritionDoseForm o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AuthorizedPharmaceuticalDoseForm", new GenericType<AuthorizedPharmaceuticalDoseForm>() {
        });
        schemas.put("NutritionDoseForm", new GenericType<NutritionDoseForm>() {
        });
        JSON.registerDescendants(MedicinalProductAllOfExtension.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return MedicinalProductAllOfExtension.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * AuthorizedPharmaceuticalDoseForm, NutritionDoseForm
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AuthorizedPharmaceuticalDoseForm.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(NutritionDoseForm.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AuthorizedPharmaceuticalDoseForm, NutritionDoseForm");
    }

    /**
     * Get the actual instance, which can be the following:
     * AuthorizedPharmaceuticalDoseForm, NutritionDoseForm
     *
     * @return The actual instance (AuthorizedPharmaceuticalDoseForm, NutritionDoseForm)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AuthorizedPharmaceuticalDoseForm`. If the actual instance is not `AuthorizedPharmaceuticalDoseForm`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AuthorizedPharmaceuticalDoseForm`
     * @throws ClassCastException if the instance is not `AuthorizedPharmaceuticalDoseForm`
     */
    public AuthorizedPharmaceuticalDoseForm getAuthorizedPharmaceuticalDoseForm() throws ClassCastException {
        return (AuthorizedPharmaceuticalDoseForm)super.getActualInstance();
    }

    /**
     * Get the actual instance of `NutritionDoseForm`. If the actual instance is not `NutritionDoseForm`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `NutritionDoseForm`
     * @throws ClassCastException if the instance is not `NutritionDoseForm`
     */
    public NutritionDoseForm getNutritionDoseForm() throws ClassCastException {
        return (NutritionDoseForm)super.getActualInstance();
    }

}

