/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Quantity is required by the FHIR R4 specification. However, as SAFEST attempts to model FHIR R5 this property is moved to ContainedItem on MedicinalProductPackaged. As such this field is included for compliance but marked as not used.
 */
@JsonPropertyOrder({
  MedicinalProductManufacturedAllOfQuantity.JSON_PROPERTY_SYSTEM,
  MedicinalProductManufacturedAllOfQuantity.JSON_PROPERTY_CODE
})
@JsonTypeName("MedicinalProductManufactured_allOf_quantity")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class MedicinalProductManufacturedAllOfQuantity {
  /**
   * URI for the unused code system to indicate this field is not in use
   */
  public enum SystemEnum {
    HTTPS_SIMPLIFIER_NET_SAFEST_UNUSEDSAFEST(URI.create("https://simplifier.net/safest/unusedsafest"));

    private URI value;

    SystemEnum(URI value) {
      this.value = value;
    }

    @JsonValue
    public URI getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SystemEnum fromValue(URI value) {
      for (SystemEnum b : SystemEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SYSTEM = "system";
  @jakarta.annotation.Nullable
  private SystemEnum system;

  /**
   * Always the NA code. Indicates that this field is not in use
   */
  public enum CodeEnum {
    NA(String.valueOf("NA"));

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CodeEnum fromValue(String value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private CodeEnum code;

  public MedicinalProductManufacturedAllOfQuantity() { 
  }

  public MedicinalProductManufacturedAllOfQuantity system(@jakarta.annotation.Nullable SystemEnum system) {
    this.system = system;
    return this;
  }

  /**
   * URI for the unused code system to indicate this field is not in use
   * @return system
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SystemEnum getSystem() {
    return system;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystem(@jakarta.annotation.Nullable SystemEnum system) {
    this.system = system;
  }


  public MedicinalProductManufacturedAllOfQuantity code(@jakarta.annotation.Nullable CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * Always the NA code. Indicates that this field is not in use
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CodeEnum getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@jakarta.annotation.Nullable CodeEnum code) {
    this.code = code;
  }


  /**
   * Return true if this MedicinalProductManufactured_allOf_quantity object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicinalProductManufacturedAllOfQuantity medicinalProductManufacturedAllOfQuantity = (MedicinalProductManufacturedAllOfQuantity) o;
    return Objects.equals(this.system, medicinalProductManufacturedAllOfQuantity.system) &&
        Objects.equals(this.code, medicinalProductManufacturedAllOfQuantity.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(system, code);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicinalProductManufacturedAllOfQuantity {\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

