/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfSubstanceExtension;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfSubstanceReferenceStrength;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Test
 */
@JsonPropertyOrder({
  MedicinalProductIngredientAllOfSubstanceStrength.JSON_PROPERTY_EXTENSION,
  MedicinalProductIngredientAllOfSubstanceStrength.JSON_PROPERTY_PRESENTATION,
  MedicinalProductIngredientAllOfSubstanceStrength.JSON_PROPERTY_CONCENTRATION,
  MedicinalProductIngredientAllOfSubstanceStrength.JSON_PROPERTY_REFERENCE_STRENGTH
})
@JsonTypeName("MedicinalProductIngredient_allOf_substance_strength")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class MedicinalProductIngredientAllOfSubstanceStrength {
  public static final String JSON_PROPERTY_EXTENSION = "extension";
  @jakarta.annotation.Nullable
  private List<MedicinalProductIngredientAllOfSubstanceExtension> extension = new ArrayList<>();

  public static final String JSON_PROPERTY_PRESENTATION = "presentation";
  @jakarta.annotation.Nullable
  private Object presentation;

  public static final String JSON_PROPERTY_CONCENTRATION = "concentration";
  @jakarta.annotation.Nullable
  private Object concentration;

  public static final String JSON_PROPERTY_REFERENCE_STRENGTH = "referenceStrength";
  @jakarta.annotation.Nullable
  private MedicinalProductIngredientAllOfSubstanceReferenceStrength referenceStrength;

  public MedicinalProductIngredientAllOfSubstanceStrength() { 
  }

  public MedicinalProductIngredientAllOfSubstanceStrength extension(@jakarta.annotation.Nullable List<MedicinalProductIngredientAllOfSubstanceExtension> extension) {
    this.extension = extension;
    return this;
  }

  public MedicinalProductIngredientAllOfSubstanceStrength addExtensionItem(MedicinalProductIngredientAllOfSubstanceExtension extensionItem) {
    if (this.extension == null) {
      this.extension = new ArrayList<>();
    }
    this.extension.add(extensionItem);
    return this;
  }

  /**
   * Extensions of the resource
   * @return extension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MedicinalProductIngredientAllOfSubstanceExtension> getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(@jakarta.annotation.Nullable List<MedicinalProductIngredientAllOfSubstanceExtension> extension) {
    this.extension = extension;
  }


  public MedicinalProductIngredientAllOfSubstanceStrength presentation(@jakarta.annotation.Nullable Object presentation) {
    this.presentation = presentation;
    return this;
  }

  /**
   * The quantity of substance in the unit of presentation
   * @return presentation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRESENTATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getPresentation() {
    return presentation;
  }


  @JsonProperty(JSON_PROPERTY_PRESENTATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPresentation(@jakarta.annotation.Nullable Object presentation) {
    this.presentation = presentation;
  }


  public MedicinalProductIngredientAllOfSubstanceStrength concentration(@jakarta.annotation.Nullable Object concentration) {
    this.concentration = concentration;
    return this;
  }

  /**
   * The strength per unitary volume
   * @return concentration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONCENTRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getConcentration() {
    return concentration;
  }


  @JsonProperty(JSON_PROPERTY_CONCENTRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConcentration(@jakarta.annotation.Nullable Object concentration) {
    this.concentration = concentration;
  }


  public MedicinalProductIngredientAllOfSubstanceStrength referenceStrength(@jakarta.annotation.Nullable MedicinalProductIngredientAllOfSubstanceReferenceStrength referenceStrength) {
    this.referenceStrength = referenceStrength;
    return this;
  }

  /**
   * Get referenceStrength
   * @return referenceStrength
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductIngredientAllOfSubstanceReferenceStrength getReferenceStrength() {
    return referenceStrength;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceStrength(@jakarta.annotation.Nullable MedicinalProductIngredientAllOfSubstanceReferenceStrength referenceStrength) {
    this.referenceStrength = referenceStrength;
  }


  /**
   * Return true if this MedicinalProductIngredient_allOf_substance_strength object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicinalProductIngredientAllOfSubstanceStrength medicinalProductIngredientAllOfSubstanceStrength = (MedicinalProductIngredientAllOfSubstanceStrength) o;
    return Objects.equals(this.extension, medicinalProductIngredientAllOfSubstanceStrength.extension) &&
        Objects.equals(this.presentation, medicinalProductIngredientAllOfSubstanceStrength.presentation) &&
        Objects.equals(this.concentration, medicinalProductIngredientAllOfSubstanceStrength.concentration) &&
        Objects.equals(this.referenceStrength, medicinalProductIngredientAllOfSubstanceStrength.referenceStrength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extension, presentation, concentration, referenceStrength);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicinalProductIngredientAllOfSubstanceStrength {\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    presentation: ").append(toIndentedString(presentation)).append("\n");
    sb.append("    concentration: ").append(toIndentedString(concentration)).append("\n");
    sb.append("    referenceStrength: ").append(toIndentedString(referenceStrength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

