/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductIngredientAllOfSubstanceReferenceStrengthSubstance;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Strength expressed in terms of a reference substance
 */
@JsonPropertyOrder({
  MedicinalProductIngredientAllOfSubstanceReferenceStrength.JSON_PROPERTY_EXTENSION,
  MedicinalProductIngredientAllOfSubstanceReferenceStrength.JSON_PROPERTY_SUBSTANCE,
  MedicinalProductIngredientAllOfSubstanceReferenceStrength.JSON_PROPERTY_STRENGTH
})
@JsonTypeName("MedicinalProductIngredient_allOf_substance_referenceStrength")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class MedicinalProductIngredientAllOfSubstanceReferenceStrength {
  public static final String JSON_PROPERTY_EXTENSION = "extension";
  @jakarta.annotation.Nullable
  private List<MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension> extension = new ArrayList<>();

  public static final String JSON_PROPERTY_SUBSTANCE = "substance";
  @jakarta.annotation.Nullable
  private MedicinalProductIngredientAllOfSubstanceReferenceStrengthSubstance substance;

  public static final String JSON_PROPERTY_STRENGTH = "strength";
  @jakarta.annotation.Nonnull
  private Object strength;

  public MedicinalProductIngredientAllOfSubstanceReferenceStrength() { 
  }

  public MedicinalProductIngredientAllOfSubstanceReferenceStrength extension(@jakarta.annotation.Nullable List<MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension> extension) {
    this.extension = extension;
    return this;
  }

  public MedicinalProductIngredientAllOfSubstanceReferenceStrength addExtensionItem(MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension extensionItem) {
    if (this.extension == null) {
      this.extension = new ArrayList<>();
    }
    this.extension.add(extensionItem);
    return this;
  }

  /**
   * Extensions of the resource
   * @return extension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension> getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(@jakarta.annotation.Nullable List<MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension> extension) {
    this.extension = extension;
  }


  public MedicinalProductIngredientAllOfSubstanceReferenceStrength substance(@jakarta.annotation.Nullable MedicinalProductIngredientAllOfSubstanceReferenceStrengthSubstance substance) {
    this.substance = substance;
    return this;
  }

  /**
   * Get substance
   * @return substance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBSTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductIngredientAllOfSubstanceReferenceStrengthSubstance getSubstance() {
    return substance;
  }


  @JsonProperty(JSON_PROPERTY_SUBSTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubstance(@jakarta.annotation.Nullable MedicinalProductIngredientAllOfSubstanceReferenceStrengthSubstance substance) {
    this.substance = substance;
  }


  public MedicinalProductIngredientAllOfSubstanceReferenceStrength strength(@jakarta.annotation.Nonnull Object strength) {
    this.strength = strength;
    return this;
  }

  /**
   * Strength expressed in terms of a reference substance
   * @return strength
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getStrength() {
    return strength;
  }


  @JsonProperty(JSON_PROPERTY_STRENGTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStrength(@jakarta.annotation.Nonnull Object strength) {
    this.strength = strength;
  }


  /**
   * Return true if this MedicinalProductIngredient_allOf_substance_referenceStrength object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicinalProductIngredientAllOfSubstanceReferenceStrength medicinalProductIngredientAllOfSubstanceReferenceStrength = (MedicinalProductIngredientAllOfSubstanceReferenceStrength) o;
    return Objects.equals(this.extension, medicinalProductIngredientAllOfSubstanceReferenceStrength.extension) &&
        Objects.equals(this.substance, medicinalProductIngredientAllOfSubstanceReferenceStrength.substance) &&
        Objects.equals(this.strength, medicinalProductIngredientAllOfSubstanceReferenceStrength.strength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extension, substance, strength);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicinalProductIngredientAllOfSubstanceReferenceStrength {\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    substance: ").append(toIndentedString(substance)).append("\n");
    sb.append("    strength: ").append(toIndentedString(strength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

