/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Link;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductListAllOfMeta;
import io.github.mjhaugsdal.eresept.fest.fhir.model.MedicinalProductPharmaceutical;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * MedicinalProductPharmaceuticalList
 */
@JsonPropertyOrder({
  MedicinalProductPharmaceuticalList.JSON_PROPERTY_RESOURCE_TYPE,
  MedicinalProductPharmaceuticalList.JSON_PROPERTY_ID,
  MedicinalProductPharmaceuticalList.JSON_PROPERTY_META,
  MedicinalProductPharmaceuticalList.JSON_PROPERTY_LINK,
  MedicinalProductPharmaceuticalList.JSON_PROPERTY_ENTRY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class MedicinalProductPharmaceuticalList {
  /**
   * The resource type
   */
  public enum ResourceTypeEnum {
    BUNDLE(String.valueOf("Bundle"));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @jakarta.annotation.Nullable
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_META = "meta";
  @jakarta.annotation.Nullable
  private MedicinalProductListAllOfMeta meta;

  public static final String JSON_PROPERTY_LINK = "link";
  @jakarta.annotation.Nullable
  private List<Link> link = new ArrayList<>();

  public static final String JSON_PROPERTY_ENTRY = "entry";
  @jakarta.annotation.Nullable
  private List<MedicinalProductPharmaceutical> entry = new ArrayList<>();

  public MedicinalProductPharmaceuticalList() { 
  }

  public MedicinalProductPharmaceuticalList resourceType(@jakarta.annotation.Nullable ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
    return this;
  }

  /**
   * The resource type
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceType(@jakarta.annotation.Nullable ResourceTypeEnum resourceType) {
    this.resourceType = resourceType;
  }


  public MedicinalProductPharmaceuticalList id(@jakarta.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * The id of the bundle.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }


  public MedicinalProductPharmaceuticalList meta(@jakarta.annotation.Nullable MedicinalProductListAllOfMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MedicinalProductListAllOfMeta getMeta() {
    return meta;
  }


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@jakarta.annotation.Nullable MedicinalProductListAllOfMeta meta) {
    this.meta = meta;
  }


  public MedicinalProductPharmaceuticalList link(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
    return this;
  }

  public MedicinalProductPharmaceuticalList addLinkItem(Link linkItem) {
    if (this.link == null) {
      this.link = new ArrayList<>();
    }
    this.link.add(linkItem);
    return this;
  }

  /**
   * Objects for pagination
   * @return link
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Link> getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(@jakarta.annotation.Nullable List<Link> link) {
    this.link = link;
  }


  public MedicinalProductPharmaceuticalList entry(@jakarta.annotation.Nullable List<MedicinalProductPharmaceutical> entry) {
    this.entry = entry;
    return this;
  }

  public MedicinalProductPharmaceuticalList addEntryItem(MedicinalProductPharmaceutical entryItem) {
    if (this.entry == null) {
      this.entry = new ArrayList<>();
    }
    this.entry.add(entryItem);
    return this;
  }

  /**
   * Array of Medicinal Product Phamaceutical resources
   * @return entry
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MedicinalProductPharmaceutical> getEntry() {
    return entry;
  }


  @JsonProperty(JSON_PROPERTY_ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntry(@jakarta.annotation.Nullable List<MedicinalProductPharmaceutical> entry) {
    this.entry = entry;
  }


  /**
   * Return true if this MedicinalProductPharmaceuticalList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicinalProductPharmaceuticalList medicinalProductPharmaceuticalList = (MedicinalProductPharmaceuticalList) o;
    return Objects.equals(this.resourceType, medicinalProductPharmaceuticalList.resourceType) &&
        Objects.equals(this.id, medicinalProductPharmaceuticalList.id) &&
        Objects.equals(this.meta, medicinalProductPharmaceuticalList.meta) &&
        Objects.equals(this.link, medicinalProductPharmaceuticalList.link) &&
        Objects.equals(this.entry, medicinalProductPharmaceuticalList.entry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, id, meta, link, entry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicinalProductPharmaceuticalList {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    entry: ").append(toIndentedString(entry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

