/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.AbstractOpenApiSchema;
import io.github.mjhaugsdal.eresept.fest.fhir.model.IsApprovedStrength;
import io.github.mjhaugsdal.eresept.fest.fhir.model.IsStrengthForMedicationGroup;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
@JsonDeserialize(using=MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension.MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtensionDeserializer.class)
@JsonSerialize(using = MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension.MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtensionSerializer.class)
public class MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension.class.getName());

    public static class MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtensionSerializer extends StdSerializer<MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension> {
        public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtensionSerializer(Class<MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension> t) {
            super(t);
        }

        public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtensionSerializer() {
            this(null);
        }

        @Override
        public void serialize(MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtensionDeserializer extends StdDeserializer<MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension> {
        public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtensionDeserializer() {
            this(MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension.class);
        }

        public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtensionDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize IsApprovedStrength
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(IsApprovedStrength.class);
                MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension ret = new MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension'", e);
            }

            // deserialize IsStrengthForMedicationGroup
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(IsStrengthForMedicationGroup.class);
                MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension ret = new MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension'", e);
            }

            throw new IOException(String.format("Failed deserialization for MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension: no match found"));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension() {
        super("anyOf", Boolean.FALSE);
    }

    public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension(IsApprovedStrength o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension(IsStrengthForMedicationGroup o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("IsApprovedStrength", new GenericType<IsApprovedStrength>() {
        });
        schemas.put("IsStrengthForMedicationGroup", new GenericType<IsStrengthForMedicationGroup>() {
        });
        JSON.registerDescendants(MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return MedicinalProductIngredientAllOfSubstanceReferenceStrengthExtension.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * IsApprovedStrength, IsStrengthForMedicationGroup
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(IsApprovedStrength.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(IsStrengthForMedicationGroup.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be IsApprovedStrength, IsStrengthForMedicationGroup");
    }

    /**
     * Get the actual instance, which can be the following:
     * IsApprovedStrength, IsStrengthForMedicationGroup
     *
     * @return The actual instance (IsApprovedStrength, IsStrengthForMedicationGroup)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `IsApprovedStrength`. If the actual instance is not `IsApprovedStrength`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IsApprovedStrength`
     * @throws ClassCastException if the instance is not `IsApprovedStrength`
     */
    public IsApprovedStrength getIsApprovedStrength() throws ClassCastException {
        return (IsApprovedStrength)super.getActualInstance();
    }

    /**
     * Get the actual instance of `IsStrengthForMedicationGroup`. If the actual instance is not `IsStrengthForMedicationGroup`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IsStrengthForMedicationGroup`
     * @throws ClassCastException if the instance is not `IsStrengthForMedicationGroup`
     */
    public IsStrengthForMedicationGroup getIsStrengthForMedicationGroup() throws ClassCastException {
        return (IsStrengthForMedicationGroup)super.getActualInstance();
    }

}

