/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeableConcept;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PackageExtensionInner;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PackageIdentifierInner;
import io.github.mjhaugsdal.eresept.fest.fhir.model.ProductShelfLife;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * A package in the package hierarchy
 */
@JsonPropertyOrder({
  ModelPackage.JSON_PROPERTY_EXTENSION,
  ModelPackage.JSON_PROPERTY_IDENTIFIER,
  ModelPackage.JSON_PROPERTY_TYPE,
  ModelPackage.JSON_PROPERTY_QUANTITY,
  ModelPackage.JSON_PROPERTY_SHELF_LIFE_STORAGE,
  ModelPackage.JSON_PROPERTY_PACKAGE_ITEM
})
@JsonTypeName("Package")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class ModelPackage {
  public static final String JSON_PROPERTY_EXTENSION = "extension";
  @jakarta.annotation.Nullable
  private List<PackageExtensionInner> extension = new ArrayList<>();

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nonnull
  private List<PackageIdentifierInner> identifier = new ArrayList<>();

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private List<CodeableConcept> type = new ArrayList<>();

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @jakarta.annotation.Nullable
  private Integer quantity;

  public static final String JSON_PROPERTY_SHELF_LIFE_STORAGE = "shelfLifeStorage";
  @jakarta.annotation.Nullable
  private List<ProductShelfLife> shelfLifeStorage = new ArrayList<>();

  public static final String JSON_PROPERTY_PACKAGE_ITEM = "packageItem";
  @jakarta.annotation.Nullable
  private List<ModelPackage> packageItem = new ArrayList<>();

  public ModelPackage() { 
  }

  public ModelPackage extension(@jakarta.annotation.Nullable List<PackageExtensionInner> extension) {
    this.extension = extension;
    return this;
  }

  public ModelPackage addExtensionItem(PackageExtensionInner extensionItem) {
    if (this.extension == null) {
      this.extension = new ArrayList<>();
    }
    this.extension.add(extensionItem);
    return this;
  }

  /**
   * Extensions for the package.
   * @return extension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PackageExtensionInner> getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(@jakarta.annotation.Nullable List<PackageExtensionInner> extension) {
    this.extension = extension;
  }


  public ModelPackage identifier(@jakarta.annotation.Nonnull List<PackageIdentifierInner> identifier) {
    this.identifier = identifier;
    return this;
  }

  public ModelPackage addIdentifierItem(PackageIdentifierInner identifierItem) {
    if (this.identifier == null) {
      this.identifier = new ArrayList<>();
    }
    this.identifier.add(identifierItem);
    return this;
  }

  /**
   * Business identifier for this product
   * @return identifier
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PackageIdentifierInner> getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifier(@jakarta.annotation.Nonnull List<PackageIdentifierInner> identifier) {
    this.identifier = identifier;
  }


  public ModelPackage type(@jakarta.annotation.Nullable List<CodeableConcept> type) {
    this.type = type;
    return this;
  }

  public ModelPackage addTypeItem(CodeableConcept typeItem) {
    if (this.type == null) {
      this.type = new ArrayList<>();
    }
    this.type.add(typeItem);
    return this;
  }

  /**
   * The type of package
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CodeableConcept> getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable List<CodeableConcept> type) {
    this.type = type;
  }


  public ModelPackage quantity(@jakarta.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Number of packaged unit
   * @return quantity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(@jakarta.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }


  public ModelPackage shelfLifeStorage(@jakarta.annotation.Nullable List<ProductShelfLife> shelfLifeStorage) {
    this.shelfLifeStorage = shelfLifeStorage;
    return this;
  }

  public ModelPackage addShelfLifeStorageItem(ProductShelfLife shelfLifeStorageItem) {
    if (this.shelfLifeStorage == null) {
      this.shelfLifeStorage = new ArrayList<>();
    }
    this.shelfLifeStorage.add(shelfLifeStorageItem);
    return this;
  }

  /**
   * Conditions for storage. Code systems from both FinnKode and SPOR
   * @return shelfLifeStorage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHELF_LIFE_STORAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProductShelfLife> getShelfLifeStorage() {
    return shelfLifeStorage;
  }


  @JsonProperty(JSON_PROPERTY_SHELF_LIFE_STORAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShelfLifeStorage(@jakarta.annotation.Nullable List<ProductShelfLife> shelfLifeStorage) {
    this.shelfLifeStorage = shelfLifeStorage;
  }


  public ModelPackage packageItem(@jakarta.annotation.Nullable List<ModelPackage> packageItem) {
    this.packageItem = packageItem;
    return this;
  }

  public ModelPackage addPackageItemItem(ModelPackage packageItemItem) {
    if (this.packageItem == null) {
      this.packageItem = new ArrayList<>();
    }
    this.packageItem.add(packageItemItem);
    return this;
  }

  /**
   * Level in the package hierarchy
   * @return packageItem
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PACKAGE_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModelPackage> getPackageItem() {
    return packageItem;
  }


  @JsonProperty(JSON_PROPERTY_PACKAGE_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackageItem(@jakarta.annotation.Nullable List<ModelPackage> packageItem) {
    this.packageItem = packageItem;
  }


  /**
   * Return true if this Package object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelPackage _package = (ModelPackage) o;
    return Objects.equals(this.extension, _package.extension) &&
        Objects.equals(this.identifier, _package.identifier) &&
        Objects.equals(this.type, _package.type) &&
        Objects.equals(this.quantity, _package.quantity) &&
        Objects.equals(this.shelfLifeStorage, _package.shelfLifeStorage) &&
        Objects.equals(this.packageItem, _package.packageItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extension, identifier, type, quantity, shelfLifeStorage, packageItem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelPackage {\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    shelfLifeStorage: ").append(toIndentedString(shelfLifeStorage)).append("\n");
    sb.append("    packageItem: ").append(toIndentedString(packageItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

