/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.AbstractOpenApiSchema;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeableConcept;
import io.github.mjhaugsdal.eresept.fest.fhir.model.NutritionCharacteristicValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Type;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
@JsonDeserialize(using=NutritionCharacteristicTypeInner.NutritionCharacteristicTypeInnerDeserializer.class)
@JsonSerialize(using = NutritionCharacteristicTypeInner.NutritionCharacteristicTypeInnerSerializer.class)
public class NutritionCharacteristicTypeInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(NutritionCharacteristicTypeInner.class.getName());

    public static class NutritionCharacteristicTypeInnerSerializer extends StdSerializer<NutritionCharacteristicTypeInner> {
        public NutritionCharacteristicTypeInnerSerializer(Class<NutritionCharacteristicTypeInner> t) {
            super(t);
        }

        public NutritionCharacteristicTypeInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(NutritionCharacteristicTypeInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class NutritionCharacteristicTypeInnerDeserializer extends StdDeserializer<NutritionCharacteristicTypeInner> {
        public NutritionCharacteristicTypeInnerDeserializer() {
            this(NutritionCharacteristicTypeInner.class);
        }

        public NutritionCharacteristicTypeInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public NutritionCharacteristicTypeInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize Type
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(Type.class);
                NutritionCharacteristicTypeInner ret = new NutritionCharacteristicTypeInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'NutritionCharacteristicTypeInner'", e);
            }

            // deserialize NutritionCharacteristicValue
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(NutritionCharacteristicValue.class);
                NutritionCharacteristicTypeInner ret = new NutritionCharacteristicTypeInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'NutritionCharacteristicTypeInner'", e);
            }

            throw new IOException(String.format("Failed deserialization for NutritionCharacteristicTypeInner: no match found"));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public NutritionCharacteristicTypeInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "NutritionCharacteristicTypeInner cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public NutritionCharacteristicTypeInner() {
        super("anyOf", Boolean.FALSE);
    }

    public NutritionCharacteristicTypeInner(Type o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public NutritionCharacteristicTypeInner(NutritionCharacteristicValue o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("NutritionCharacteristicValue", new GenericType<NutritionCharacteristicValue>() {
        });
        schemas.put("Type", new GenericType<Type>() {
        });
        JSON.registerDescendants(NutritionCharacteristicTypeInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return NutritionCharacteristicTypeInner.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * NutritionCharacteristicValue, Type
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Type.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(NutritionCharacteristicValue.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be NutritionCharacteristicValue, Type");
    }

    /**
     * Get the actual instance, which can be the following:
     * NutritionCharacteristicValue, Type
     *
     * @return The actual instance (NutritionCharacteristicValue, Type)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Type`. If the actual instance is not `Type`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Type`
     * @throws ClassCastException if the instance is not `Type`
     */
    public Type getType() throws ClassCastException {
        return (Type)super.getActualInstance();
    }

    /**
     * Get the actual instance of `NutritionCharacteristicValue`. If the actual instance is not `NutritionCharacteristicValue`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `NutritionCharacteristicValue`
     * @throws ClassCastException if the instance is not `NutritionCharacteristicValue`
     */
    public NutritionCharacteristicValue getNutritionCharacteristicValue() throws ClassCastException {
        return (NutritionCharacteristicValue)super.getActualInstance();
    }

}

