/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Uses a code system to identify the type of resource
 */
@JsonPropertyOrder({
  NutritionProductAllOfCode.JSON_PROPERTY_SYSTEM,
  NutritionProductAllOfCode.JSON_PROPERTY_CODE,
  NutritionProductAllOfCode.JSON_PROPERTY_DISPLAY
})
@JsonTypeName("NutritionProduct_allOf_code")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class NutritionProductAllOfCode {
  /**
   * Code system for basic type
   */
  public enum SystemEnum {
    HTTPS_API_LEGEMIDDELVERKET_NO_FHIR_R4_CODE_SYSTEM_CC4DA87F_DD48_404F_80C3_7ECD22395CF0(URI.create("https://api.legemiddelverket.no/FHIR-R4/CodeSystem/cc4da87f-dd48-404f-80c3-7ecd22395cf0"));

    private URI value;

    SystemEnum(URI value) {
      this.value = value;
    }

    @JsonValue
    public URI getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SystemEnum fromValue(URI value) {
      for (SystemEnum b : SystemEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SYSTEM = "system";
  @jakarta.annotation.Nullable
  private SystemEnum system;

  /**
   * Always 1 for nutrition product
   */
  public enum CodeEnum {
    NUMBER_1(Integer.valueOf(1));

    private Integer value;

    CodeEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CodeEnum fromValue(Integer value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private CodeEnum code;

  /**
   * Always Nutrition Product
   */
  public enum DisplayEnum {
    NUTRITION_PRODUCT(String.valueOf("Nutrition Product"));

    private String value;

    DisplayEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DisplayEnum fromValue(String value) {
      for (DisplayEnum b : DisplayEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DISPLAY = "display";
  @jakarta.annotation.Nullable
  private DisplayEnum display;

  public NutritionProductAllOfCode() { 
  }

  public NutritionProductAllOfCode system(@jakarta.annotation.Nullable SystemEnum system) {
    this.system = system;
    return this;
  }

  /**
   * Code system for basic type
   * @return system
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SystemEnum getSystem() {
    return system;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystem(@jakarta.annotation.Nullable SystemEnum system) {
    this.system = system;
  }


  public NutritionProductAllOfCode code(@jakarta.annotation.Nullable CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * Always 1 for nutrition product
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CodeEnum getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@jakarta.annotation.Nullable CodeEnum code) {
    this.code = code;
  }


  public NutritionProductAllOfCode display(@jakarta.annotation.Nullable DisplayEnum display) {
    this.display = display;
    return this;
  }

  /**
   * Always Nutrition Product
   * @return display
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DisplayEnum getDisplay() {
    return display;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplay(@jakarta.annotation.Nullable DisplayEnum display) {
    this.display = display;
  }


  /**
   * Return true if this NutritionProduct_allOf_code object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NutritionProductAllOfCode nutritionProductAllOfCode = (NutritionProductAllOfCode) o;
    return Objects.equals(this.system, nutritionProductAllOfCode.system) &&
        Objects.equals(this.code, nutritionProductAllOfCode.code) &&
        Objects.equals(this.display, nutritionProductAllOfCode.display);
  }

  @Override
  public int hashCode() {
    return Objects.hash(system, code, display);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NutritionProductAllOfCode {\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

