/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.AbstractOpenApiSchema;
import io.github.mjhaugsdal.eresept.fest.fhir.model.DataCarrierIdentifier;
import io.github.mjhaugsdal.eresept.fest.fhir.model.SafestPackagedItemID;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
@JsonDeserialize(using=PackageIdentifierInner.PackageIdentifierInnerDeserializer.class)
@JsonSerialize(using = PackageIdentifierInner.PackageIdentifierInnerSerializer.class)
public class PackageIdentifierInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(PackageIdentifierInner.class.getName());

    public static class PackageIdentifierInnerSerializer extends StdSerializer<PackageIdentifierInner> {
        public PackageIdentifierInnerSerializer(Class<PackageIdentifierInner> t) {
            super(t);
        }

        public PackageIdentifierInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(PackageIdentifierInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class PackageIdentifierInnerDeserializer extends StdDeserializer<PackageIdentifierInner> {
        public PackageIdentifierInnerDeserializer() {
            this(PackageIdentifierInner.class);
        }

        public PackageIdentifierInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public PackageIdentifierInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize SafestPackagedItemID
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(SafestPackagedItemID.class);
                PackageIdentifierInner ret = new PackageIdentifierInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'PackageIdentifierInner'", e);
            }

            // deserialize DataCarrierIdentifier
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(DataCarrierIdentifier.class);
                PackageIdentifierInner ret = new PackageIdentifierInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'PackageIdentifierInner'", e);
            }

            throw new IOException(String.format("Failed deserialization for PackageIdentifierInner: no match found"));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public PackageIdentifierInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "PackageIdentifierInner cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public PackageIdentifierInner() {
        super("anyOf", Boolean.FALSE);
    }

    public PackageIdentifierInner(SafestPackagedItemID o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PackageIdentifierInner(DataCarrierIdentifier o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("DataCarrierIdentifier", new GenericType<DataCarrierIdentifier>() {
        });
        schemas.put("SafestPackagedItemID", new GenericType<SafestPackagedItemID>() {
        });
        JSON.registerDescendants(PackageIdentifierInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return PackageIdentifierInner.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * DataCarrierIdentifier, SafestPackagedItemID
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(SafestPackagedItemID.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DataCarrierIdentifier.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be DataCarrierIdentifier, SafestPackagedItemID");
    }

    /**
     * Get the actual instance, which can be the following:
     * DataCarrierIdentifier, SafestPackagedItemID
     *
     * @return The actual instance (DataCarrierIdentifier, SafestPackagedItemID)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `SafestPackagedItemID`. If the actual instance is not `SafestPackagedItemID`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SafestPackagedItemID`
     * @throws ClassCastException if the instance is not `SafestPackagedItemID`
     */
    public SafestPackagedItemID getSafestPackagedItemID() throws ClassCastException {
        return (SafestPackagedItemID)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DataCarrierIdentifier`. If the actual instance is not `DataCarrierIdentifier`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DataCarrierIdentifier`
     * @throws ClassCastException if the instance is not `DataCarrierIdentifier`
     */
    public DataCarrierIdentifier getDataCarrierIdentifier() throws ClassCastException {
        return (DataCarrierIdentifier)super.getActualInstance();
    }

}

