/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.AbstractOpenApiSchema;
import io.github.mjhaugsdal.eresept.fest.fhir.model.ContainedItem;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Property;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
@JsonDeserialize(using=PackageExtensionInner.PackageExtensionInnerDeserializer.class)
@JsonSerialize(using = PackageExtensionInner.PackageExtensionInnerSerializer.class)
public class PackageExtensionInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(PackageExtensionInner.class.getName());

    public static class PackageExtensionInnerSerializer extends StdSerializer<PackageExtensionInner> {
        public PackageExtensionInnerSerializer(Class<PackageExtensionInner> t) {
            super(t);
        }

        public PackageExtensionInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(PackageExtensionInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class PackageExtensionInnerDeserializer extends StdDeserializer<PackageExtensionInner> {
        public PackageExtensionInnerDeserializer() {
            this(PackageExtensionInner.class);
        }

        public PackageExtensionInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public PackageExtensionInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize Property
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(Property.class);
                PackageExtensionInner ret = new PackageExtensionInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'PackageExtensionInner'", e);
            }

            // deserialize ContainedItem
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(ContainedItem.class);
                PackageExtensionInner ret = new PackageExtensionInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'PackageExtensionInner'", e);
            }

            throw new IOException(String.format("Failed deserialization for PackageExtensionInner: no match found"));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public PackageExtensionInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "PackageExtensionInner cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public PackageExtensionInner() {
        super("anyOf", Boolean.FALSE);
    }

    public PackageExtensionInner(Property o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PackageExtensionInner(ContainedItem o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("ContainedItem", new GenericType<ContainedItem>() {
        });
        schemas.put("Property", new GenericType<Property>() {
        });
        JSON.registerDescendants(PackageExtensionInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return PackageExtensionInner.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * ContainedItem, Property
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Property.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(ContainedItem.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be ContainedItem, Property");
    }

    /**
     * Get the actual instance, which can be the following:
     * ContainedItem, Property
     *
     * @return The actual instance (ContainedItem, Property)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Property`. If the actual instance is not `Property`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Property`
     * @throws ClassCastException if the instance is not `Property`
     */
    public Property getProperty() throws ClassCastException {
        return (Property)super.getActualInstance();
    }

    /**
     * Get the actual instance of `ContainedItem`. If the actual instance is not `ContainedItem`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ContainedItem`
     * @throws ClassCastException if the instance is not `ContainedItem`
     */
    public ContainedItem getContainedItem() throws ClassCastException {
        return (ContainedItem)super.getActualInstance();
    }

}

