/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * PlanDefinitionAllOfExtension
 */
@JsonPropertyOrder({
  PlanDefinitionAllOfExtension.JSON_PROPERTY_URL,
  PlanDefinitionAllOfExtension.JSON_PROPERTY_VALUE_STRING,
  PlanDefinitionAllOfExtension.JSON_PROPERTY_VALUE_INTEGER,
  PlanDefinitionAllOfExtension.JSON_PROPERTY_SHI_GUIDELINE_RANK
})
@JsonTypeName("PlanDefinition_allOf_extension")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class PlanDefinitionAllOfExtension {
  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_VALUE_STRING = "valueString";
  @jakarta.annotation.Nullable
  private String valueString;

  public static final String JSON_PROPERTY_VALUE_INTEGER = "valueInteger";
  @jakarta.annotation.Nullable
  private Integer valueInteger;

  public static final String JSON_PROPERTY_SHI_GUIDELINE_RANK = "shiGuidelineRank";
  @jakarta.annotation.Nullable
  private Integer shiGuidelineRank;

  public PlanDefinitionAllOfExtension() { 
  }

  public PlanDefinitionAllOfExtension url(@jakarta.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }


  public PlanDefinitionAllOfExtension valueString(@jakarta.annotation.Nullable String valueString) {
    this.valueString = valueString;
    return this;
  }

  /**
   * Get valueString
   * @return valueString
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueString() {
    return valueString;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueString(@jakarta.annotation.Nullable String valueString) {
    this.valueString = valueString;
  }


  public PlanDefinitionAllOfExtension valueInteger(@jakarta.annotation.Nullable Integer valueInteger) {
    this.valueInteger = valueInteger;
    return this;
  }

  /**
   * Get valueInteger
   * @return valueInteger
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_INTEGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getValueInteger() {
    return valueInteger;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_INTEGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueInteger(@jakarta.annotation.Nullable Integer valueInteger) {
    this.valueInteger = valueInteger;
  }


  public PlanDefinitionAllOfExtension shiGuidelineRank(@jakarta.annotation.Nullable Integer shiGuidelineRank) {
    this.shiGuidelineRank = shiGuidelineRank;
    return this;
  }

  /**
   * The rank value for the treatment alternative from Sykehusinnkjøp. More details can be found [here](https://simplifier.net/interregionalt-h-resept-prosjekt/shiguidelinerank).
   * @return shiGuidelineRank
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHI_GUIDELINE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getShiGuidelineRank() {
    return shiGuidelineRank;
  }


  @JsonProperty(JSON_PROPERTY_SHI_GUIDELINE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShiGuidelineRank(@jakarta.annotation.Nullable Integer shiGuidelineRank) {
    this.shiGuidelineRank = shiGuidelineRank;
  }


  /**
   * Return true if this PlanDefinition_allOf_extension object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanDefinitionAllOfExtension planDefinitionAllOfExtension = (PlanDefinitionAllOfExtension) o;
    return Objects.equals(this.url, planDefinitionAllOfExtension.url) &&
        Objects.equals(this.valueString, planDefinitionAllOfExtension.valueString) &&
        Objects.equals(this.valueInteger, planDefinitionAllOfExtension.valueInteger) &&
        Objects.equals(this.shiGuidelineRank, planDefinitionAllOfExtension.shiGuidelineRank);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, valueString, valueInteger, shiGuidelineRank);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanDefinitionAllOfExtension {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    valueString: ").append(toIndentedString(valueString)).append("\n");
    sb.append("    valueInteger: ").append(toIndentedString(valueInteger)).append("\n");
    sb.append("    shiGuidelineRank: ").append(toIndentedString(shiGuidelineRank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

