/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * PlanDefinitionAllOfEffectivePeriod
 */
@JsonPropertyOrder({
  PlanDefinitionAllOfEffectivePeriod.JSON_PROPERTY_START,
  PlanDefinitionAllOfEffectivePeriod.JSON_PROPERTY_END
})
@JsonTypeName("PlanDefinition_allOf_effectivePeriod")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class PlanDefinitionAllOfEffectivePeriod {
  public static final String JSON_PROPERTY_START = "start";
  @jakarta.annotation.Nullable
  private LocalDate start;

  public static final String JSON_PROPERTY_END = "end";
  @jakarta.annotation.Nullable
  private LocalDate end;

  public PlanDefinitionAllOfEffectivePeriod() { 
  }

  public PlanDefinitionAllOfEffectivePeriod start(@jakarta.annotation.Nullable LocalDate start) {
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getStart() {
    return start;
  }


  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStart(@jakarta.annotation.Nullable LocalDate start) {
    this.start = start;
  }


  public PlanDefinitionAllOfEffectivePeriod end(@jakarta.annotation.Nullable LocalDate end) {
    this.end = end;
    return this;
  }

  /**
   * Get end
   * @return end
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getEnd() {
    return end;
  }


  @JsonProperty(JSON_PROPERTY_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnd(@jakarta.annotation.Nullable LocalDate end) {
    this.end = end;
  }


  /**
   * Return true if this PlanDefinition_allOf_effectivePeriod object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanDefinitionAllOfEffectivePeriod planDefinitionAllOfEffectivePeriod = (PlanDefinitionAllOfEffectivePeriod) o;
    return Objects.equals(this.start, planDefinitionAllOfEffectivePeriod.start) &&
        Objects.equals(this.end, planDefinitionAllOfEffectivePeriod.end);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, end);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanDefinitionAllOfEffectivePeriod {\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

