/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PlanDefinitionAllOfEffectivePeriod;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PlanDefinitionAllOfExtension;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PlanDefinitionAllOfGoal;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PlanDefinitionAllOfIdentifier;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PlanDefinitionAllOfMeta;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PlanDefinitionAllOfType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * PlanDefinition
 */
@JsonPropertyOrder({
  PlanDefinition.JSON_PROPERTY_RESOURCE_TYPE,
  PlanDefinition.JSON_PROPERTY_ID,
  PlanDefinition.JSON_PROPERTY_META,
  PlanDefinition.JSON_PROPERTY_EXTENSION,
  PlanDefinition.JSON_PROPERTY_IDENTIFIER,
  PlanDefinition.JSON_PROPERTY_NAME,
  PlanDefinition.JSON_PROPERTY_TITLE,
  PlanDefinition.JSON_PROPERTY_TYPE,
  PlanDefinition.JSON_PROPERTY_STATUS,
  PlanDefinition.JSON_PROPERTY_PUBLISHER,
  PlanDefinition.JSON_PROPERTY_DESCRIPTION,
  PlanDefinition.JSON_PROPERTY_JURISDICTION,
  PlanDefinition.JSON_PROPERTY_EFFECTIVE_PERIOD,
  PlanDefinition.JSON_PROPERTY_GOAL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class PlanDefinition {
  /**
   * The resource type
   */
  public enum ResourceTypeEnum {
    PLAN_DEFINITION(String.valueOf("PlanDefinition"));

    private String value;

    ResourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResourceTypeEnum fromValue(String value) {
      for (ResourceTypeEnum b : ResourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resourceType";
  @jakarta.annotation.Nullable
  private ResourceTypeEnum resourceType;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_META = "meta";
  @jakarta.annotation.Nullable
  private PlanDefinitionAllOfMeta meta;

  public static final String JSON_PROPERTY_EXTENSION = "extension";
  @jakarta.annotation.Nullable
  private List<PlanDefinitionAllOfExtension> extension = new ArrayList<>();

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nullable
  private List<PlanDefinitionAllOfIdentifier> identifier = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private PlanDefinitionAllOfType type;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_PUBLISHER = "publisher";
  @jakarta.annotation.Nullable
  private String publisher;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_JURISDICTION = "jurisdiction";
  @jakarta.annotation.Nullable
  private List<PlanDefinitionAllOfType> jurisdiction = new ArrayList<>();

  public static final String JSON_PROPERTY_EFFECTIVE_PERIOD = "effectivePeriod";
  @jakarta.annotation.Nullable
  private PlanDefinitionAllOfEffectivePeriod effectivePeriod;

  public static final String JSON_PROPERTY_GOAL = "goal";
  @jakarta.annotation.Nullable
  private List<PlanDefinitionAllOfGoal> goal = new ArrayList<>();

  public PlanDefinition() { 
  }

  @JsonCreator
  public PlanDefinition(
    @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE) ResourceTypeEnum resourceType, 
    @JsonProperty(JSON_PROPERTY_ID) String id
  ) {
    this();
    this.resourceType = resourceType;
    this.id = id;
  }

  /**
   * The resource type
   * @return resourceType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceTypeEnum getResourceType() {
    return resourceType;
  }




  /**
   * Id of the resource
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }




  public PlanDefinition meta(@jakarta.annotation.Nullable PlanDefinitionAllOfMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlanDefinitionAllOfMeta getMeta() {
    return meta;
  }


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@jakarta.annotation.Nullable PlanDefinitionAllOfMeta meta) {
    this.meta = meta;
  }


  public PlanDefinition extension(@jakarta.annotation.Nullable List<PlanDefinitionAllOfExtension> extension) {
    this.extension = extension;
    return this;
  }

  public PlanDefinition addExtensionItem(PlanDefinitionAllOfExtension extensionItem) {
    if (this.extension == null) {
      this.extension = new ArrayList<>();
    }
    this.extension.add(extensionItem);
    return this;
  }

  /**
   * Get extension
   * @return extension
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlanDefinitionAllOfExtension> getExtension() {
    return extension;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtension(@jakarta.annotation.Nullable List<PlanDefinitionAllOfExtension> extension) {
    this.extension = extension;
  }


  public PlanDefinition identifier(@jakarta.annotation.Nullable List<PlanDefinitionAllOfIdentifier> identifier) {
    this.identifier = identifier;
    return this;
  }

  public PlanDefinition addIdentifierItem(PlanDefinitionAllOfIdentifier identifierItem) {
    if (this.identifier == null) {
      this.identifier = new ArrayList<>();
    }
    this.identifier.add(identifierItem);
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlanDefinitionAllOfIdentifier> getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifier(@jakarta.annotation.Nullable List<PlanDefinitionAllOfIdentifier> identifier) {
    this.identifier = identifier;
  }


  public PlanDefinition name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * General description of disease group.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public PlanDefinition title(@jakarta.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Name of treatment group.
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }


  public PlanDefinition type(@jakarta.annotation.Nullable PlanDefinitionAllOfType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlanDefinitionAllOfType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable PlanDefinitionAllOfType type) {
    this.type = type;
  }


  public PlanDefinition status(@jakarta.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Publication status of the resource. Either &#39;draft, active, retired eller unknown&#39;.
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public PlanDefinition publisher(@jakarta.annotation.Nullable String publisher) {
    this.publisher = publisher;
    return this;
  }

  /**
   * Who publishes the treatment options. Always &#39;Sykehusinnkjøp&#39;.
   * @return publisher
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublisher() {
    return publisher;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublisher(@jakarta.annotation.Nullable String publisher) {
    this.publisher = publisher;
  }


  public PlanDefinition description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Description of the resource.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public PlanDefinition jurisdiction(@jakarta.annotation.Nullable List<PlanDefinitionAllOfType> jurisdiction) {
    this.jurisdiction = jurisdiction;
    return this;
  }

  public PlanDefinition addJurisdictionItem(PlanDefinitionAllOfType jurisdictionItem) {
    if (this.jurisdiction == null) {
      this.jurisdiction = new ArrayList<>();
    }
    this.jurisdiction.add(jurisdictionItem);
    return this;
  }

  /**
   * Get jurisdiction
   * @return jurisdiction
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JURISDICTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlanDefinitionAllOfType> getJurisdiction() {
    return jurisdiction;
  }


  @JsonProperty(JSON_PROPERTY_JURISDICTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJurisdiction(@jakarta.annotation.Nullable List<PlanDefinitionAllOfType> jurisdiction) {
    this.jurisdiction = jurisdiction;
  }


  public PlanDefinition effectivePeriod(@jakarta.annotation.Nullable PlanDefinitionAllOfEffectivePeriod effectivePeriod) {
    this.effectivePeriod = effectivePeriod;
    return this;
  }

  /**
   * Get effectivePeriod
   * @return effectivePeriod
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlanDefinitionAllOfEffectivePeriod getEffectivePeriod() {
    return effectivePeriod;
  }


  @JsonProperty(JSON_PROPERTY_EFFECTIVE_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEffectivePeriod(@jakarta.annotation.Nullable PlanDefinitionAllOfEffectivePeriod effectivePeriod) {
    this.effectivePeriod = effectivePeriod;
  }


  public PlanDefinition goal(@jakarta.annotation.Nullable List<PlanDefinitionAllOfGoal> goal) {
    this.goal = goal;
    return this;
  }

  public PlanDefinition addGoalItem(PlanDefinitionAllOfGoal goalItem) {
    if (this.goal == null) {
      this.goal = new ArrayList<>();
    }
    this.goal.add(goalItem);
    return this;
  }

  /**
   * Get goal
   * @return goal
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GOAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlanDefinitionAllOfGoal> getGoal() {
    return goal;
  }


  @JsonProperty(JSON_PROPERTY_GOAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGoal(@jakarta.annotation.Nullable List<PlanDefinitionAllOfGoal> goal) {
    this.goal = goal;
  }


  /**
   * Return true if this PlanDefinition object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanDefinition planDefinition = (PlanDefinition) o;
    return Objects.equals(this.resourceType, planDefinition.resourceType) &&
        Objects.equals(this.id, planDefinition.id) &&
        Objects.equals(this.meta, planDefinition.meta) &&
        Objects.equals(this.extension, planDefinition.extension) &&
        Objects.equals(this.identifier, planDefinition.identifier) &&
        Objects.equals(this.name, planDefinition.name) &&
        Objects.equals(this.title, planDefinition.title) &&
        Objects.equals(this.type, planDefinition.type) &&
        Objects.equals(this.status, planDefinition.status) &&
        Objects.equals(this.publisher, planDefinition.publisher) &&
        Objects.equals(this.description, planDefinition.description) &&
        Objects.equals(this.jurisdiction, planDefinition.jurisdiction) &&
        Objects.equals(this.effectivePeriod, planDefinition.effectivePeriod) &&
        Objects.equals(this.goal, planDefinition.goal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, id, meta, extension, identifier, name, title, type, status, publisher, description, jurisdiction, effectivePeriod, goal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanDefinition {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    jurisdiction: ").append(toIndentedString(jurisdiction)).append("\n");
    sb.append("    effectivePeriod: ").append(toIndentedString(effectivePeriod)).append("\n");
    sb.append("    goal: ").append(toIndentedString(goal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

