/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PlanDefinitionAllOfDescription;
import io.github.mjhaugsdal.eresept.fest.fhir.model.PlanDefinitionAllOfType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * PlanDefinitionAllOfGoal
 */
@JsonPropertyOrder({
  PlanDefinitionAllOfGoal.JSON_PROPERTY_DESCRIPTION,
  PlanDefinitionAllOfGoal.JSON_PROPERTY_ADDRESSES
})
@JsonTypeName("PlanDefinition_allOf_goal")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class PlanDefinitionAllOfGoal {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private PlanDefinitionAllOfDescription description;

  public static final String JSON_PROPERTY_ADDRESSES = "addresses";
  @jakarta.annotation.Nullable
  private List<PlanDefinitionAllOfType> addresses = new ArrayList<>();

  public PlanDefinitionAllOfGoal() { 
  }

  public PlanDefinitionAllOfGoal description(@jakarta.annotation.Nullable PlanDefinitionAllOfDescription description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlanDefinitionAllOfDescription getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable PlanDefinitionAllOfDescription description) {
    this.description = description;
  }


  public PlanDefinitionAllOfGoal addresses(@jakarta.annotation.Nullable List<PlanDefinitionAllOfType> addresses) {
    this.addresses = addresses;
    return this;
  }

  public PlanDefinitionAllOfGoal addAddressesItem(PlanDefinitionAllOfType addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

  /**
   * Get addresses
   * @return addresses
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlanDefinitionAllOfType> getAddresses() {
    return addresses;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddresses(@jakarta.annotation.Nullable List<PlanDefinitionAllOfType> addresses) {
    this.addresses = addresses;
  }


  /**
   * Return true if this PlanDefinition_allOf_goal object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanDefinitionAllOfGoal planDefinitionAllOfGoal = (PlanDefinitionAllOfGoal) o;
    return Objects.equals(this.description, planDefinitionAllOfGoal.description) &&
        Objects.equals(this.addresses, planDefinitionAllOfGoal.addresses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, addresses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanDefinitionAllOfGoal {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

