/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.RatioDenominator;
import io.github.mjhaugsdal.eresept.fest.fhir.model.RatioNumerator;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * A relationship between two Quantity values expressed as a numerator and a denominator.
 */
@JsonPropertyOrder({
  Ratio.JSON_PROPERTY_NUMERATOR,
  Ratio.JSON_PROPERTY_DENOMINATOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class Ratio {
  public static final String JSON_PROPERTY_NUMERATOR = "numerator";
  @jakarta.annotation.Nullable
  private RatioNumerator numerator;

  public static final String JSON_PROPERTY_DENOMINATOR = "denominator";
  @jakarta.annotation.Nullable
  private RatioDenominator denominator;

  public Ratio() { 
  }

  public Ratio numerator(@jakarta.annotation.Nullable RatioNumerator numerator) {
    this.numerator = numerator;
    return this;
  }

  /**
   * Get numerator
   * @return numerator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RatioNumerator getNumerator() {
    return numerator;
  }


  @JsonProperty(JSON_PROPERTY_NUMERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumerator(@jakarta.annotation.Nullable RatioNumerator numerator) {
    this.numerator = numerator;
  }


  public Ratio denominator(@jakarta.annotation.Nullable RatioDenominator denominator) {
    this.denominator = denominator;
    return this;
  }

  /**
   * Get denominator
   * @return denominator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DENOMINATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RatioDenominator getDenominator() {
    return denominator;
  }


  @JsonProperty(JSON_PROPERTY_DENOMINATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDenominator(@jakarta.annotation.Nullable RatioDenominator denominator) {
    this.denominator = denominator;
  }


  /**
   * Return true if this Ratio object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ratio ratio = (Ratio) o;
    return Objects.equals(this.numerator, ratio.numerator) &&
        Objects.equals(this.denominator, ratio.denominator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numerator, denominator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ratio {\n");
    sb.append("    numerator: ").append(toIndentedString(numerator)).append("\n");
    sb.append("    denominator: ").append(toIndentedString(denominator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

