/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Describes the language of the name in this object
 */
@JsonPropertyOrder({
  SubstanceSpecificationAllOfExtension1.JSON_PROPERTY_URL,
  SubstanceSpecificationAllOfExtension1.JSON_PROPERTY_VALUE_STRING
})
@JsonTypeName("SubstanceSpecification_allOf_extension_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class SubstanceSpecificationAllOfExtension1 {
  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private URI url;

  public static final String JSON_PROPERTY_VALUE_STRING = "valueString";
  @jakarta.annotation.Nullable
  private String valueString;

  public SubstanceSpecificationAllOfExtension1() { 
  }

  public SubstanceSpecificationAllOfExtension1 url(@jakarta.annotation.Nullable URI url) {
    this.url = url;
    return this;
  }

  /**
   * Defines the type of the extension
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable URI url) {
    this.url = url;
  }


  public SubstanceSpecificationAllOfExtension1 valueString(@jakarta.annotation.Nullable String valueString) {
    this.valueString = valueString;
    return this;
  }

  /**
   * An alias is created if the substance has both an English and a Norwegian name that ends in &#39;ion&#39;. The alias will be the name where the &#39;ion&#39; suffix has been removed.
   * @return valueString
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueString() {
    return valueString;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueString(@jakarta.annotation.Nullable String valueString) {
    this.valueString = valueString;
  }


  /**
   * Return true if this SubstanceSpecification_allOf_extension_1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubstanceSpecificationAllOfExtension1 substanceSpecificationAllOfExtension1 = (SubstanceSpecificationAllOfExtension1) o;
    return Objects.equals(this.url, substanceSpecificationAllOfExtension1.url) &&
        Objects.equals(this.valueString, substanceSpecificationAllOfExtension1.valueString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, valueString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubstanceSpecificationAllOfExtension1 {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    valueString: ").append(toIndentedString(valueString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

