/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * SAFEST generated ID for the substance
 */
@JsonPropertyOrder({
  SubstanceSpecificationAllOfIdentifier.JSON_PROPERTY_SYSTEM,
  SubstanceSpecificationAllOfIdentifier.JSON_PROPERTY_VALUE
})
@JsonTypeName("SubstanceSpecification_allOf_identifier")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class SubstanceSpecificationAllOfIdentifier {
  public static final String JSON_PROPERTY_SYSTEM = "system";
  @jakarta.annotation.Nullable
  private URI system;

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nullable
  private String value;

  public SubstanceSpecificationAllOfIdentifier() { 
  }

  public SubstanceSpecificationAllOfIdentifier system(@jakarta.annotation.Nullable URI system) {
    this.system = system;
    return this;
  }

  /**
   * http://legemiddelverket.no/fhir/SAFEST/SafestSubstanceDefinitionID
   * @return system
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getSystem() {
    return system;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystem(@jakarta.annotation.Nullable URI system) {
    this.system = system;
  }


  public SubstanceSpecificationAllOfIdentifier value(@jakarta.annotation.Nullable String value) {
    this.value = value;
    return this;
  }

  /**
   * The SAFEST ID
   * @return value
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@jakarta.annotation.Nullable String value) {
    this.value = value;
  }


  /**
   * Return true if this SubstanceSpecification_allOf_identifier object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubstanceSpecificationAllOfIdentifier substanceSpecificationAllOfIdentifier = (SubstanceSpecificationAllOfIdentifier) o;
    return Objects.equals(this.system, substanceSpecificationAllOfIdentifier.system) &&
        Objects.equals(this.value, substanceSpecificationAllOfIdentifier.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(system, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubstanceSpecificationAllOfIdentifier {\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

