/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.AbstractOpenApiSchema;
import io.github.mjhaugsdal.eresept.fest.fhir.model.CodeableConcept;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Coding;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;

import com.fasterxml.jackson.core.type.TypeReference;

import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
@JsonDeserialize(using = SubstanceSpecificationAllOfLanguage.SubstanceSpecificationAllOfLanguageDeserializer.class)
@JsonSerialize(using = SubstanceSpecificationAllOfLanguage.SubstanceSpecificationAllOfLanguageSerializer.class)
public class SubstanceSpecificationAllOfLanguage extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SubstanceSpecificationAllOfLanguage.class.getName());

    public static class SubstanceSpecificationAllOfLanguageSerializer extends StdSerializer<SubstanceSpecificationAllOfLanguage> {
        public SubstanceSpecificationAllOfLanguageSerializer(Class<SubstanceSpecificationAllOfLanguage> t) {
            super(t);
        }

        public SubstanceSpecificationAllOfLanguageSerializer() {
            this(null);
        }

        @Override
        public void serialize(SubstanceSpecificationAllOfLanguage value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SubstanceSpecificationAllOfLanguageDeserializer extends StdDeserializer<SubstanceSpecificationAllOfLanguage> {
        public SubstanceSpecificationAllOfLanguageDeserializer() {
            this(SubstanceSpecificationAllOfLanguage.class);
        }

        public SubstanceSpecificationAllOfLanguageDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public SubstanceSpecificationAllOfLanguage deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize CodeableConcept
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CodeableConcept.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CodeableConcept'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CodeableConcept'", e);
            }

            if (match == 1) {
                SubstanceSpecificationAllOfLanguage ret = new SubstanceSpecificationAllOfLanguage();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for SubstanceSpecificationAllOfLanguage: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public SubstanceSpecificationAllOfLanguage getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "SubstanceSpecificationAllOfLanguage cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public SubstanceSpecificationAllOfLanguage() {
        super("oneOf", Boolean.FALSE);
    }

    public SubstanceSpecificationAllOfLanguage(CodeableConcept o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("CodeableConcept", new GenericType<CodeableConcept>() {
        });
        JSON.registerDescendants(SubstanceSpecificationAllOfLanguage.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return SubstanceSpecificationAllOfLanguage.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * CodeableConcept
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(CodeableConcept.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be CodeableConcept");
    }

    /**
     * Get the actual instance, which can be the following:
     * CodeableConcept
     *
     * @return The actual instance (CodeableConcept)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `CodeableConcept`. If the actual instance is not `CodeableConcept`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CodeableConcept`
     * @throws ClassCastException if the instance is not `CodeableConcept`
     */
    public CodeableConcept getCodeableConcept() throws ClassCastException {
        return (CodeableConcept)super.getActualInstance();
    }

}

