/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.SubstanceSpecificationAllOfReference;
import io.github.mjhaugsdal.eresept.fest.fhir.model.SubstanceSpecificationAllOfType1;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * SubstanceSpecificationAllOfRelationship
 */
@JsonPropertyOrder({
  SubstanceSpecificationAllOfRelationship.JSON_PROPERTY_TYPE,
  SubstanceSpecificationAllOfRelationship.JSON_PROPERTY_REFERENCE
})
@JsonTypeName("SubstanceSpecification_allOf_relationship")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class SubstanceSpecificationAllOfRelationship {
  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private SubstanceSpecificationAllOfType1 type;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  @jakarta.annotation.Nullable
  private SubstanceSpecificationAllOfReference reference;

  public SubstanceSpecificationAllOfRelationship() { 
  }

  public SubstanceSpecificationAllOfRelationship type(@jakarta.annotation.Nullable SubstanceSpecificationAllOfType1 type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SubstanceSpecificationAllOfType1 getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable SubstanceSpecificationAllOfType1 type) {
    this.type = type;
  }


  public SubstanceSpecificationAllOfRelationship reference(@jakarta.annotation.Nullable SubstanceSpecificationAllOfReference reference) {
    this.reference = reference;
    return this;
  }

  /**
   * Get reference
   * @return reference
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SubstanceSpecificationAllOfReference getReference() {
    return reference;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReference(@jakarta.annotation.Nullable SubstanceSpecificationAllOfReference reference) {
    this.reference = reference;
  }


  /**
   * Return true if this SubstanceSpecification_allOf_relationship object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubstanceSpecificationAllOfRelationship substanceSpecificationAllOfRelationship = (SubstanceSpecificationAllOfRelationship) o;
    return Objects.equals(this.type, substanceSpecificationAllOfRelationship.type) &&
        Objects.equals(this.reference, substanceSpecificationAllOfRelationship.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, reference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubstanceSpecificationAllOfRelationship {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

