/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.Quantity;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Value is a Quantity
 */
@JsonPropertyOrder({
  ValueQuantity.JSON_PROPERTY_VALUE_QUANTITY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class ValueQuantity {
  public static final String JSON_PROPERTY_VALUE_QUANTITY = "valueQuantity";
  @jakarta.annotation.Nullable
  private Quantity valueQuantity;

  public ValueQuantity() { 
  }

  public ValueQuantity valueQuantity(@jakarta.annotation.Nullable Quantity valueQuantity) {
    this.valueQuantity = valueQuantity;
    return this;
  }

  /**
   * Get valueQuantity
   * @return valueQuantity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Quantity getValueQuantity() {
    return valueQuantity;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueQuantity(@jakarta.annotation.Nullable Quantity valueQuantity) {
    this.valueQuantity = valueQuantity;
  }


  /**
   * Return true if this ValueQuantity object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValueQuantity valueQuantity = (ValueQuantity) o;
    return Objects.equals(this.valueQuantity, valueQuantity.valueQuantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valueQuantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValueQuantity {\n");
    sb.append("    valueQuantity: ").append(toIndentedString(valueQuantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

