/*
 * FHIR-R4
 * Formålet med gjennomføringsprosjektet er å etablere og tilgjengeliggjøre én kilde til strukturert legemiddelinformasjon for kravområdene Datakvalitet, Virkestoffordinering, Produktkoder, og Ernæring, Kobling mellom substans og ATC-kode og formidling av H-reseptinformasjon.
 *
 * The version of the OpenAPI document: 
 * Contact: FEST@dmp.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mjhaugsdal.eresept.fest.fhir.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.mjhaugsdal.eresept.fest.fhir.model.ValueSetAllOfComposeInclude;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.mjhaugsdal.eresept.fest.fhir.JSON;


/**
 * Content-logical definition of the value set.
 */
@JsonPropertyOrder({
  ValueSetAllOfCompose.JSON_PROPERTY_INACTIVE,
  ValueSetAllOfCompose.JSON_PROPERTY_INCLUDE
})
@JsonTypeName("ValueSet_allOf_compose")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T11:23:23.733753200+02:00[Europe/Oslo]", comments = "Generator version: 7.12.0")
public class ValueSetAllOfCompose {
  public static final String JSON_PROPERTY_INACTIVE = "inactive";
  @jakarta.annotation.Nullable
  private Boolean inactive;

  public static final String JSON_PROPERTY_INCLUDE = "include";
  @jakarta.annotation.Nonnull
  private List<ValueSetAllOfComposeInclude> include = new ArrayList<>();

  public ValueSetAllOfCompose() { 
  }

  public ValueSetAllOfCompose inactive(@jakarta.annotation.Nullable Boolean inactive) {
    this.inactive = inactive;
    return this;
  }

  /**
   * Defines whether the value set contains inactive codes. This will always be false as only active codes are published in SAFEST
   * @return inactive
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInactive() {
    return inactive;
  }


  @JsonProperty(JSON_PROPERTY_INACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInactive(@jakarta.annotation.Nullable Boolean inactive) {
    this.inactive = inactive;
  }


  public ValueSetAllOfCompose include(@jakarta.annotation.Nonnull List<ValueSetAllOfComposeInclude> include) {
    this.include = include;
    return this;
  }

  public ValueSetAllOfCompose addIncludeItem(ValueSetAllOfComposeInclude includeItem) {
    if (this.include == null) {
      this.include = new ArrayList<>();
    }
    this.include.add(includeItem);
    return this;
  }

  /**
   * Used to include codes from one or more code systems in the value set
   * @return include
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INCLUDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ValueSetAllOfComposeInclude> getInclude() {
    return include;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInclude(@jakarta.annotation.Nonnull List<ValueSetAllOfComposeInclude> include) {
    this.include = include;
  }


  /**
   * Return true if this ValueSet_allOf_compose object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValueSetAllOfCompose valueSetAllOfCompose = (ValueSetAllOfCompose) o;
    return Objects.equals(this.inactive, valueSetAllOfCompose.inactive) &&
        Objects.equals(this.include, valueSetAllOfCompose.include);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inactive, include);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValueSetAllOfCompose {\n");
    sb.append("    inactive: ").append(toIndentedString(inactive)).append("\n");
    sb.append("    include: ").append(toIndentedString(include)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

