apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonLabels:
  app.kubernetes.io/string: infrastructure

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: mock-service
    behavior: create